export interface ItineraryDay {
  day: number;
  title: string;
  activities: string[];
  tips?: string;
}

export interface Travel {
  id: number;
  country: string;
  city: string;
  region: string | null;
  visitedYear: number;
  coverImageUrl: string;
  secondaryImageUrl: string | null;
  galleryImages: string[];
  summary: string;
  tags: string[];
  itinerary: ItineraryDay[];
  highlights: string[];
  practicalInfo: string | null;
  createdAt: string;
}

export const travels: Travel[] = [
  {
    id: 1,
    country: "Japan",
    city: "Tokyo",
    region: "Kanto",
    visitedYear: 2025,
    coverImageUrl: "/images/travel-tokyo.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Tokyo is sensory overload in the best possible way — neon lights and quiet temple gardens existing in perfect tension.",
    tags: ["Asia", "food", "culture", "city"],
    itinerary: [
      { day: 1, title: "Arrival & Shibuya", activities: ["Arrive at Narita/Haneda", "Check in Shinjuku hotel", "Shibuya crossing at night", "Ramen dinner"], tips: "Get a Suica IC card at the airport — use it for all trains and convenience stores." },
      { day: 2, title: "Asakusa & Akihabara", activities: ["Senso-ji Temple at dawn", "Nakamise shopping street", "Akihabara electronics district", "Tsukiji Outer Market for sushi"], tips: "Asakusa is best at 7am before the crowds arrive." },
      { day: 3, title: "Harajuku & Shibuya Deep Dive", activities: ["Meiji Shrine", "Harajuku Takeshita Street", "Omotesando for shopping", "TeamLab Borderless digital art"], tips: "Book TeamLab weeks in advance." },
    ],
    highlights: ["Shibuya crossing at midnight is surreal", "Tsukiji sushi at 7am", "Vending machines at every corner"],
    practicalInfo: "No visa required for US passport holders (90 days). Carry cash — Japan is still largely cash-based. IC Suica card is essential.",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 2,
    country: "Japan",
    city: "Osaka",
    region: "Kansai",
    visitedYear: 2025,
    coverImageUrl: "/images/travel-osaka.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Osaka's energy is infectious — a city that lives to eat and laughs louder than anyone else in Japan.",
    tags: ["Asia", "food", "nightlife", "culture"],
    itinerary: [
      { day: 1, title: "Dotonbori & Street Food", activities: ["Dotonbori canal walk", "Takoyaki from Kukuru", "Osaka Castle grounds", "Namba nightlife"], tips: "Dotonbori comes alive after 6pm." },
      { day: 2, title: "Shinsekai & Kuromon Market", activities: ["Kuromon Ichiba Market for breakfast", "Shinsekai district", "Sumiyoshi Taisha shrine", "Kushikatsu dinner"], tips: "Never double-dip the kushikatsu — house rules." },
    ],
    highlights: ["Dotonbori at night", "Takoyaki as a food group", "Friendliest city in Japan"],
    practicalInfo: "40-minute shinkansen from Kyoto. Stay in Namba for walking access to everything.",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 3,
    country: "Japan",
    city: "Kyoto",
    region: "Kansai",
    visitedYear: 2025,
    coverImageUrl: "/images/travel-kyoto.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Kyoto in autumn is one of those places that makes you quiet. Every temple, every stone path, every torii gate feels deliberate.",
    tags: ["Asia", "temples", "nature", "history"],
    itinerary: [
      { day: 1, title: "Arashiyama", activities: ["Bamboo Grove at sunrise", "Tenryu-ji Temple garden", "Boat ride on Oi River", "Gion district at dusk"], tips: "Bamboo Grove is magical before 7:30am. After 9am it's crowded." },
      { day: 2, title: "Fushimi Inari & Nishiki", activities: ["Fushimi Inari full hike (3 hrs)", "Kinkaku-ji Golden Pavilion", "Nishiki Market food tour", "Tea ceremony experience"], tips: "Book tea ceremony in advance. Fushimi Inari takes 2-3 hours for the full loop." },
    ],
    highlights: ["Fushimi Inari at sunrise", "Autumn leaves at every shrine", "Kaiseki dinner"],
    practicalInfo: "15 min from Osaka by shinkansen. Rent a bicycle to cover the city. Best in March (cherry blossom) or November (koyo).",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 4,
    country: "Italy",
    city: "Rome",
    region: "Lazio",
    visitedYear: 2023,
    coverImageUrl: "/images/travel-rome.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Rome layers thousands of years on top of each other so naturally that you forget you're eating gelato next to ruins that predate Christianity.",
    tags: ["Europe", "history", "food", "art"],
    itinerary: [
      { day: 1, title: "Ancient Rome", activities: ["Colosseum & Roman Forum (book in advance)", "Palatine Hill", "Gelato near the Pantheon", "Trastevere dinner"], tips: "Book Colosseum tickets weeks ahead." },
      { day: 2, title: "Vatican & Piazzas", activities: ["Vatican Museums & Sistine Chapel (early entry)", "St. Peter's Basilica", "Piazza Navona", "Campo de' Fiori market"], tips: "First entry at Vatican opens at 8am — get there early." },
      { day: 3, title: "Hidden Rome", activities: ["Borghese Gallery (reservation required)", "Trastevere neighborhood walk", "Aperitivo hour", "Cacio e pepe dinner"], tips: "Borghese requires timed entry — book well in advance." },
    ],
    highlights: ["The Pantheon at dawn", "Cacio e pepe done right", "Trastevere cobblestone at dusk"],
    practicalInfo: "No visa required for US passport holders in Schengen zone. Book major museums weeks in advance.",
    createdAt: "2023-01-01T00:00:00Z",
  },
  {
    id: 5,
    country: "Italy",
    city: "Florence",
    region: "Tuscany",
    visitedYear: 2023,
    coverImageUrl: "/images/travel-florence.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Florence is smaller than you expect and more beautiful than you can prepare for. Every street corner is a painting.",
    tags: ["Europe", "art", "food", "history"],
    itinerary: [
      { day: 1, title: "Uffizi & Duomo", activities: ["Uffizi Gallery (book in advance)", "Brunelleschi's Dome climb", "Mercato Centrale for lunch", "Ponte Vecchio at golden hour"], tips: "Climb the Duomo dome for the best view of Florence." },
      { day: 2, title: "Oltrarno & Tuscany", activities: ["Pitti Palace & Boboli Gardens", "Oltrarno neighborhood craft shops", "Sunset from Piazzale Michelangelo", "Bistecca alla Fiorentina dinner"], tips: "Piazzale Michelangelo at sunset is unmissable." },
    ],
    highlights: ["Boboli Gardens in morning light", "Gelato from Gelateria dei Neri", "The David (worth every queue)"],
    practicalInfo: "90 minutes from Rome by high-speed train. Florence is walkable — no metro needed.",
    createdAt: "2023-01-01T00:00:00Z",
  },
  {
    id: 6,
    country: "Italy",
    city: "Milan",
    region: "Lombardy",
    visitedYear: 2023,
    coverImageUrl: "/images/travel-milan.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Milan surprised me — I expected fashion runways and got centuries of art, the world's best aperitivo scene, and a city that moves fast but lives well.",
    tags: ["Europe", "fashion", "food", "art"],
    itinerary: [
      { day: 1, title: "Duomo & Design Quarter", activities: ["Duomo di Milano rooftop tour", "Galleria Vittorio Emanuele II", "Aperitivo in Brera district", "Risotto alla Milanese dinner"], tips: "Book Duomo rooftop in advance — worth it for the view." },
      { day: 2, title: "The Last Supper", activities: ["Santa Maria delle Grazie (The Last Supper)", "Sforzesco Castle", "Navigli canals evening stroll", "Spritz and cicchetti"], tips: "Last Supper tickets sell out months ahead — book online before your trip." },
    ],
    highlights: ["The Last Supper in person is surreal", "Aperitivo hour with free snacks everywhere", "Rooftop Duomo views"],
    practicalInfo: "Visa-free in Schengen. Book The Last Supper months in advance — no exceptions.",
    createdAt: "2023-01-01T00:00:00Z",
  },
  {
    id: 7,
    country: "Italy",
    city: "Venice",
    region: "Veneto",
    visitedYear: 2023,
    coverImageUrl: "/images/travel-venice.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Venice is the kind of place that should feel like a tourist trap but instead completely disarms you. Getting lost in the alleys is the whole point — and the canals at sunrise are magical.",
    tags: ["Europe", "history", "architecture", "culture", "Italy"],
    itinerary: [],
    highlights: ["Sunrise walk along the Grand Canal before the crowds", "Getting deliberately lost in Dorsoduro", "Gondola ride at dusk (yes, it's touristy — do it anyway)"],
    practicalInfo: "Venice is expensive. Arrive early, stay late, and avoid midday in summer. The vaporetto water buses are the best way to get around. Skip the tourist restaurants and find where locals eat.",
    createdAt: "2023-01-01T00:00:00Z",
  },
  {
    id: 8,
    country: "Norway",
    city: "Oslo",
    region: "Eastern Norway",
    visitedYear: 2022,
    coverImageUrl: "/images/travel-oslo.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Oslo is a city that takes the outdoors seriously. Clean, walkable, and surrounded by fjords and forests — it changed the way I think about city planning.",
    tags: ["Europe", "Scandinavia", "nature", "design"],
    itinerary: [
      { day: 1, title: "Museums & Waterfront", activities: ["Vigeland Sculpture Park", "Viking Ship Museum", "Aker Brygge waterfront", "Seafood dinner"], tips: "Oslo Pass covers most museum entries and transit." },
      { day: 2, title: "Fjord Day Trip", activities: ["Ferry to Bygdøy peninsula", "Fram Museum (polar exploration)", "Kayaking on Oslofjord", "Mathallen Food Hall"], tips: "Fjord kayaking tours run May through September." },
    ],
    highlights: ["Vigeland Park is unlike anything anywhere", "The midnight sun in summer", "Oslofjord by ferry"],
    practicalInfo: "No Schengen visa required. Oslo is expensive — budget €30+ for a meal. Oslo Pass is essential.",
    createdAt: "2022-01-01T00:00:00Z",
  },
  {
    id: 9,
    country: "Norway",
    city: "Ålesund",
    region: "Møre og Romsdal",
    visitedYear: 2022,
    coverImageUrl: "/images/travel-alesund.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Ålesund sits on a cluster of islands and is one of the most beautiful towns I've ever seen — Art Nouveau architecture, colorful harbor views, and the sea in every direction.",
    tags: ["Europe", "architecture", "nature", "fjords", "Norway"],
    itinerary: [],
    highlights: ["Aksla viewpoint for the full panorama over the archipelago", "Jugendstilsenteret Art Nouveau museum", "Fresh seafood at the harbor"],
    practicalInfo: "Ålesund is a common stop on Norway coastal cruises but equally great as a base. It's a small city — very walkable. The hike up to Aksla is 418 steps and absolutely worth it.",
    createdAt: "2022-01-01T00:00:00Z",
  },
  {
    id: 10,
    country: "Norway",
    city: "Geiranger",
    region: "Møre og Romsdal",
    visitedYear: 2022,
    coverImageUrl: "/images/travel-geiranger.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Geiranger is a place you think can't possibly be real — a tiny village deep in one of the most dramatic fjords on earth, with waterfalls spilling into the water from every direction.",
    tags: ["Europe", "nature", "fjords", "adventure", "Norway"],
    itinerary: [],
    highlights: ["Boat tour through the UNESCO-listed Geirangerfjord", "The Seven Sisters and Suitor waterfalls", "Via Ferrata climbing above the fjord"],
    practicalInfo: "Geiranger is tiny and gets crowded in summer — arrive early or late in the day. The winding Trollstigen road nearby is one of the most dramatic drives in the world.",
    createdAt: "2022-01-01T00:00:00Z",
  },
  {
    id: 11,
    country: "Norway",
    city: "Loen",
    region: "Vestland",
    visitedYear: 2022,
    coverImageUrl: "/images/travel-loen.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Loen is a hidden gem — a quiet village in western Norway where the fjord meets the mountains and the views from the gondola are among the most spectacular I've ever seen.",
    tags: ["Europe", "nature", "fjords", "hiking", "Norway"],
    itinerary: [],
    highlights: ["Loen Skylift gondola to the summit of Mount Hoven", "Kayaking on Lovatnet glacial lake", "Via Ferrata on Hoven mountain"],
    practicalInfo: "Loen is a small village but has excellent infrastructure for outdoor activities. The Skylift gondola is worth every krone.",
    createdAt: "2022-01-01T00:00:00Z",
  },
  {
    id: 12,
    country: "Norway",
    city: "Stranda",
    region: "Møre og Romsdal",
    visitedYear: 2022,
    coverImageUrl: "/images/travel-stranda.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Stranda is a fjord town that most visitors drive through on the way to Geiranger — which means it stays wonderfully quiet. The scenery is just as stunning.",
    tags: ["Europe", "nature", "fjords", "Norway"],
    itinerary: [],
    highlights: ["Stranda Fjord views", "Gateway to Sunnylven Fjord", "Old Town wooden buildings"],
    practicalInfo: "Stranda is often used as a base for exploring the surrounding fjords. The ferry crossing to Geiranger is a scenic journey in itself.",
    createdAt: "2022-01-01T00:00:00Z",
  },
  {
    id: 13,
    country: "Switzerland",
    city: "Grindelwald",
    region: "Bernese Oberland",
    visitedYear: 2023,
    coverImageUrl: "/images/travel-grindelwald.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Grindelwald sits in a valley with the Eiger looming over it like a painting. I hiked trails I had no business hiking and felt entirely alive.",
    tags: ["Europe", "mountains", "hiking", "nature"],
    itinerary: [
      { day: 1, title: "Arrival & First Hike", activities: ["Arrive by train from Interlaken", "Bachalpsee Lake hike (4 hrs round trip)", "Dinner in village with Eiger views"], tips: "The Bachalpsee hike is one of the most beautiful in Switzerland." },
      { day: 2, title: "Jungfraujoch", activities: ["Cogwheel train to Jungfraujoch (Top of Europe, 3454m)", "Ice Palace inside the glacier", "Views of Aletsch Glacier", "Return via Kleine Scheidegg"], tips: "Check weather before booking — clouds can obscure all views." },
    ],
    highlights: ["Eiger views from the village square", "Bachalpsee at golden hour", "Jungfraujoch glacier ice palace"],
    practicalInfo: "Accessible by train from Interlaken in 45 minutes. Swiss Travel Pass covers most mountain railways.",
    createdAt: "2023-01-01T00:00:00Z",
  },
  {
    id: 14,
    country: "Switzerland",
    city: "Interlaken",
    region: "Bernese Oberland",
    visitedYear: 2023,
    coverImageUrl: "/images/travel-interlaken.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Interlaken is the adventure sports capital of Switzerland — sandwiched between two lakes and a mountain range that dares you to climb it.",
    tags: ["Europe", "adventure", "mountains", "nature"],
    itinerary: [
      { day: 1, title: "Lakes & Town", activities: ["Boat ride on Lake Brienz", "Höhematte park walk", "Paragliding (book in advance)", "Fondue dinner"], tips: "Paragliding from Beatenberg offers stunning views of both lakes." },
    ],
    highlights: ["Paragliding over two lakes simultaneously", "Train rides through mountain tunnels", "Every direction is a postcard"],
    practicalInfo: "Central hub for the Bernese Oberland region. Book adventure activities in advance in peak summer season.",
    createdAt: "2023-01-01T00:00:00Z",
  },
  {
    id: 15,
    country: "Switzerland",
    city: "Lauterbrunnen",
    region: "Bernese Oberland",
    visitedYear: 2023,
    coverImageUrl: "/images/travel-lauterbrunnen.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "72 waterfalls tumbling down sheer cliff walls into a valley so green it looks fictional. Lauterbrunnen is the Switzerland no one tells you about.",
    tags: ["Europe", "waterfalls", "nature", "hiking"],
    itinerary: [
      { day: 1, title: "Valley of 72 Waterfalls", activities: ["Staubbach Falls walk", "Trümmelbach Falls (inside the mountain)", "Wengen village by train", "Sunset from valley floor"], tips: "Trümmelbach Falls are inside a mountain — completely unexpected and unmissable." },
    ],
    highlights: ["Waterfalls literally falling off cliffs everywhere", "Trümmelbach inside the mountain", "The valley is Lord of the Rings levels of beautiful"],
    practicalInfo: "Cars are not permitted in the valley — park in Lauterbrunnen and take trains. 15 min from Interlaken.",
    createdAt: "2023-01-01T00:00:00Z",
  },
  {
    id: 16,
    country: "Spain",
    city: "Madrid",
    region: "Community of Madrid",
    visitedYear: 2019,
    coverImageUrl: "/images/travel-madrid.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Madrid has the best art museums in Europe and a lunch culture that lasts until 4pm. I leaned into both completely.",
    tags: ["Europe", "art", "food", "nightlife"],
    itinerary: [
      { day: 1, title: "The Golden Triangle of Art", activities: ["Prado Museum (3+ hours)", "Reina Sofia for Guernica", "Thyssen-Bornemisza", "Tapas in La Latina"], tips: "The Prado alone could take a full day — prioritize your favorite periods." },
      { day: 2, title: "Royal Madrid", activities: ["Royal Palace exterior & gardens", "Mercado de San Miguel", "Retiro Park afternoon", "Late dinner (don't arrive before 9pm)"], tips: "Madrileños don't eat dinner until 10pm. Embrace it." },
    ],
    highlights: ["Guernica at Reina Sofia", "Churros con chocolate at San Ginés", "Retiro Park on a Sunday"],
    practicalInfo: "Schengen visa-free. Madrid is very walkable between major museums. Metro is fast and cheap.",
    createdAt: "2019-01-01T00:00:00Z",
  },
  {
    id: 17,
    country: "Spain",
    city: "Granada",
    region: "Andalusia",
    visitedYear: 2019,
    coverImageUrl: "/images/travel-granada.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Granada carries centuries of Moorish architecture with breathtaking ease. The Alhambra sits above the city like a crown, and the tapas are free with every drink.",
    tags: ["Europe", "history", "Moorish", "architecture"],
    itinerary: [
      { day: 1, title: "The Alhambra", activities: ["Alhambra Palace & Generalife Gardens (morning slot)", "Alcazaba fortress", "El Bañuelo Arab baths", "Free tapas dinner in El Realejo"], tips: "Book Alhambra tickets months in advance — they sell out constantly." },
      { day: 2, title: "Albaicín & Sacromonte", activities: ["Albaicín neighborhood walking tour", "Mirador de San Nicolás (sunset view of Alhambra)", "Flamenco show in Sacromonte cave", "Arabic tea house in the Moorish quarter"], tips: "Mirador de San Nicolás at sunset with the Alhambra lit up is one of the best views in Europe." },
    ],
    highlights: ["Alhambra palace at sunrise light", "Free tapas culture — only in Granada", "Flamenco in a cave"],
    practicalInfo: "3-hour bus from Seville or 1.5 hours from Malaga. Book Alhambra tickets the moment you confirm your travel dates.",
    createdAt: "2019-01-01T00:00:00Z",
  },
  {
    id: 18,
    country: "Spain",
    city: "Seville",
    region: "Andalusia",
    visitedYear: 2019,
    coverImageUrl: "/images/travel-seville.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Seville is the most romantic city in Spain — orange trees, flamenco echoing from bars, and the largest Gothic cathedral in the world.",
    tags: ["Europe", "history", "food", "flamenco"],
    itinerary: [
      { day: 1, title: "Cathedral & Alcázar", activities: ["Seville Cathedral & La Giralda tower climb", "Real Alcázar palace", "Barrio Santa Cruz neighborhood", "Tapas bar crawl"], tips: "Climb La Giralda for 360° views over the city." },
      { day: 2, title: "Triana & Flamenco", activities: ["Triana market breakfast", "Guadalquivir river walk", "Flamenco show at El Arenal or Tablao", "Farewell dinner in Alameda de Hércules"], tips: "Book flamenco shows in advance for good seats." },
    ],
    highlights: ["La Giralda tower at sunset", "Authentic flamenco — not the tourist version", "Orange blossom smell everywhere in spring"],
    practicalInfo: "High-speed train from Madrid (2.5 hours). Seville is best explored on foot or by bicycle.",
    createdAt: "2019-01-01T00:00:00Z",
  },
  {
    id: 19,
    country: "Spain",
    city: "Córdoba",
    region: "Andalusia",
    visitedYear: 2019,
    coverImageUrl: "/images/travel-cordoba.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Córdoba's Mezquita is one of the most extraordinary buildings I have ever walked into — a mosque built over by a cathedral, coexisting for centuries.",
    tags: ["Europe", "history", "Moorish", "architecture"],
    itinerary: [
      { day: 1, title: "The Mezquita & Old City", activities: ["Mezquita-Catedral (morning entry)", "Alcázar de los Reyes Cristianos", "Jewish Quarter walk", "Salmorejo lunch (Cordoba's version of gazpacho)"], tips: "The Mezquita is best experienced with a guided tour to understand its layered history." },
    ],
    highlights: ["The Mezquita's forest of red-and-white arches", "The flower-filled patios in May", "Salmorejo is superior gazpacho"],
    practicalInfo: "Day trip from Seville (45 min by high-speed train) or Granada (2 hours). Worth a night if possible.",
    createdAt: "2019-01-01T00:00:00Z",
  },
  {
    id: 20,
    country: "France",
    city: "Paris",
    region: "Île-de-France",
    visitedYear: 2023,
    coverImageUrl: "/images/travel-paris.jpg",
    secondaryImageUrl: "/images/travel-paris-2.jpg",
    galleryImages: [],
    summary: "Paris is exactly what everyone says it is, and somehow still manages to exceed expectations. Every arrondissement has a different personality and all of them are beautiful.",
    tags: ["Europe", "food", "art", "city", "culture"],
    itinerary: [],
    highlights: ["Musée d'Orsay over the Louvre", "Canal Saint-Martin neighborhood", "Père Lachaise at golden hour", "Marché des Enfants Rouges"],
    practicalInfo: "Paris Métro is efficient and inexpensive. Get a carnet of 10 tickets. Most museums are closed on Mondays.",
    createdAt: "2023-01-01T00:00:00Z",
  },
  {
    id: 21,
    country: "United Kingdom",
    city: "London",
    region: "England",
    visitedYear: 2025,
    coverImageUrl: "/images/travel-london.jpg",
    secondaryImageUrl: "/images/travel-london-2.jpg",
    galleryImages: [],
    summary: "London is a city that earns its reputation every single time. History, culture, incredible food from every corner of the world, and a pace that matches yours.",
    tags: ["Europe", "history", "food", "culture", "city"],
    itinerary: [],
    highlights: ["Borough Market for every kind of food imaginable", "The British Museum (and it's free)", "Walking across Tower Bridge at dusk"],
    practicalInfo: "No visa required for US passport holders (6 months). Oyster card or contactless for the Tube. Mind the gap.",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 22,
    country: "United Kingdom",
    city: "Liverpool",
    region: "England",
    visitedYear: 2025,
    coverImageUrl: "/images/travel-liverpool.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Liverpool punches way above its weight. A port city with an outsized cultural footprint — The Beatles, football, and a waterfront that genuinely takes your breath away.",
    tags: ["Europe", "history", "culture", "music", "city"],
    itinerary: [],
    highlights: ["The Beatles Story museum at the Albert Dock", "Anfield on matchday — an experience unlike any other", "Albert Dock at sunset over the Mersey"],
    practicalInfo: "About 2 hours from London by train. Very walkable city center. Scouse accents are thick and wonderful.",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 23,
    country: "United Kingdom",
    city: "Manchester",
    region: "England",
    visitedYear: 2025,
    coverImageUrl: "/images/travel-manchester.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Manchester has the energy of a city always proving something — gritty, creative, and deeply proud. The food scene has completely transformed, and the Northern Quarter is endlessly cool.",
    tags: ["Europe", "culture", "food", "music", "city"],
    itinerary: [],
    highlights: ["Northern Quarter for coffee, street art, and vintage shops", "Manchester Art Gallery — free and fantastic", "The Arndale and Manchester Christmas Markets"],
    practicalInfo: "About 2 hours from London by train. Very walkable between neighbourhoods. Rainy — always pack a layer.",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 24,
    country: "Malaysia",
    city: "Kuala Lumpur",
    region: "Wilayah Persekutuan",
    visitedYear: 2025,
    coverImageUrl: "/images/travel-kuala-lumpur.jpg",
    secondaryImageUrl: "/images/travel-kuala-lumpur-2.jpg",
    galleryImages: [],
    summary: "KL is impossibly diverse — Malay, Chinese, Indian, and expat cultures colliding in the most delicious, colorful, chaotic way. I could eat my way through it for weeks.",
    tags: ["Asia", "food", "culture", "city"],
    itinerary: [
      { day: 1, title: "Petronas & City Center", activities: ["Petronas Twin Towers (book sky bridge in advance)", "KLCC Park walk", "Bukit Bintang night market", "Hawker stall dinner — char kway teow and roti canai"], tips: "Book Petronas sky bridge tickets online — they sell out." },
      { day: 2, title: "Batu Caves & Little India", activities: ["Batu Caves Hindu temple climb (272 steps)", "Little India in Brickfields", "Central Market for craft shopping", "Rooftop bar with Twin Towers view at dusk"], tips: "Batu Caves dress modestly — temple etiquette applies." },
    ],
    highlights: ["Petronas at night is iconic for a reason", "Batu Caves is an entire vibe", "The food is unmatched, full stop"],
    practicalInfo: "No visa required for US passport holders (90 days). Grab (rideshare) is essential. English is widely spoken.",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 25,
    country: "Singapore",
    city: "Singapore",
    region: "Central Region",
    visitedYear: 2025,
    coverImageUrl: "/images/travel-singapore.jpg",
    secondaryImageUrl: "/images/travel-singapore-2.jpg",
    galleryImages: [],
    summary: "Singapore is the most efficient city I have ever visited — impeccably clean, impossibly organized, and full of food that quietly rearranges your expectations.",
    tags: ["Asia", "food", "city", "gardens"],
    itinerary: [
      { day: 1, title: "Gardens & Marina Bay", activities: ["Gardens by the Bay (Flower Dome & Cloud Forest)", "Marina Bay Sands SkyPark for city views", "Hawker Centre dinner — chicken rice & laksa", "Light show at Gardens by the Bay (free, 8pm & 9pm)"], tips: "The light show at Supertrees is free — don't miss it." },
      { day: 2, title: "Neighborhoods", activities: ["Chinatown morning (Sri Mariamman Temple)", "Little India's Mustafa Centre", "Kampong Glam & Sultan Mosque", "Clarke Quay riverfront evening"], tips: "Singapore's neighborhoods are each distinct cultural worlds — walk slowly." },
    ],
    highlights: ["Gardens by the Bay is futuristic and beautiful", "Chicken rice from a hawker stall is a revelation", "Changi Airport is its own attraction"],
    practicalInfo: "No visa required for US passport holders. Singapore is expensive — budget accordingly. MRT is fast and extensive.",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 26,
    country: "Indonesia",
    city: "Bali",
    region: "Lesser Sunda Islands",
    visitedYear: 2025,
    coverImageUrl: "/images/travel-bali.jpg",
    secondaryImageUrl: "/images/travel-bali-2.jpg",
    galleryImages: [],
    summary: "Bali offers something for everyone but takes something specific from you — it asks you to slow down, and you eventually stop resisting.",
    tags: ["Asia", "beaches", "temples", "yoga"],
    itinerary: [
      { day: 1, title: "Ubud & Rice Terraces", activities: ["Tegallalang Rice Terraces (early morning)", "Ubud Monkey Forest", "Ubud Market for crafts", "Traditional Balinese dance performance"], tips: "Visit Tegallalang before 8am to avoid tour groups." },
      { day: 2, title: "Temple Day", activities: ["Tanah Lot sea temple at sunset", "Uluwatu cliff-top temple", "Kecak fire dance at Uluwatu", "Seminyak beach dinner"], tips: "Kecak dance at Uluwatu at sunset is one of Bali's unmissable experiences — book in advance." },
    ],
    highlights: ["Uluwatu at sunset with the Kecak dance", "Tegallalang rice terraces at golden hour", "Ubud's healing energy is real"],
    practicalInfo: "Visa on arrival for US passport holders (30 days, ~$35). Hire a driver for the day (~$40) rather than relying on Grab.",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 27,
    country: "South Korea",
    city: "Seoul",
    region: "Seoul Capital Area",
    visitedYear: 2024,
    coverImageUrl: "/images/travel-seoul.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Seoul operates on a different frequency — K-beauty, skincare temples, 4am street food, palaces next to glass skyscrapers, and the best fried chicken of my life.",
    tags: ["Asia", "food", "culture", "K-pop", "city"],
    itinerary: [
      { day: 1, title: "Palaces & Hongdae", activities: ["Gyeongbokgung Palace (try on hanbok)", "Bukchon Hanok Village", "Insadong for craft shopping", "Hongdae nightlife and street food"], tips: "Rent a hanbok at Gyeongbokgung — you get free entry wearing one." },
      { day: 2, title: "Myeongdong & N Seoul Tower", activities: ["Myeongdong for K-beauty shopping", "Namdaemun Market", "N Seoul Tower at sunset", "Korean BBQ dinner in Mapo-gu"], tips: "Korean BBQ is best with a group — go with at least 2 people." },
    ],
    highlights: ["Fried chicken + beer (chimaek) is a food religion here", "Gyeongbokgung Palace in hanbok", "Hongdae at midnight — the whole city is awake"],
    practicalInfo: "No visa required for US passport holders (90 days). T-money card for all public transit. English signage on subway.",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 28,
    country: "Pakistan",
    city: "Karachi",
    region: "Sindh",
    visitedYear: 2022,
    coverImageUrl: "/images/travel-karachi.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Karachi is a city of 15 million that runs on chai, biryani, and an unshakeable sense of itself. Loud, layered, and alive in a way few cities match.",
    tags: ["Asia", "Pakistan", "food", "culture", "city"],
    itinerary: [],
    highlights: ["Clifton Beach at sunset", "Burns Road for the best food in the city", "Mohatta Palace Museum"],
    practicalInfo: "Visa required for US passport holders — apply in advance. Summers are hot; winter (November–February) is ideal. Stay in Defence or Clifton area.",
    createdAt: "2022-01-01T00:00:00Z",
  },
  {
    id: 29,
    country: "Pakistan",
    city: "Lahore",
    region: "Punjab",
    visitedYear: 2022,
    coverImageUrl: "/images/travel-lahore.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Lahore is Pakistan's cultural heart — Mughal architecture, incredible street food, and a creative energy that's impossible to ignore once you've felt it.",
    tags: ["Asia", "Pakistan", "history", "food", "culture"],
    itinerary: [],
    highlights: ["Badshahi Mosque at dawn", "Lahore Fort & Sheesh Mahal", "Food Street in the old city"],
    practicalInfo: "An hour's flight from Karachi. The Old City is best explored by foot or rickshaw — motorized traffic makes driving challenging. Don't miss Cooco's Den.",
    createdAt: "2022-01-01T00:00:00Z",
  },
  {
    id: 30,
    country: "Canada",
    city: "Banff",
    region: "Alberta",
    visitedYear: 2025,
    coverImageUrl: "/images/travel-banff.jpg",
    secondaryImageUrl: "/images/travel-banff-2.jpg",
    galleryImages: ["/images/travel-banff-3.jpg"],
    summary: "Banff looks like it was designed by someone who had never seen nature before and overcorrected wildly. Turquoise lakes, glacier peaks, elk walking downtown.",
    tags: ["North America", "mountains", "hiking", "nature"],
    itinerary: [
      { day: 1, title: "Lake Louise & Moraine Lake", activities: ["Moraine Lake at sunrise (arrive by 6am)", "Lake Louise shoreline walk", "Fairview Lookout hike", "Banff town evening walk"], tips: "Moraine Lake road requires a Parks Canada shuttle reservation — book months ahead." },
      { day: 2, title: "Icefields Parkway", activities: ["Drive the Icefields Parkway (world's most scenic road)", "Athabasca Glacier walk", "Peyto Lake viewpoint", "Jasper town for dinner"], tips: "Stop at every pullout on Icefields Parkway — every single one." },
    ],
    highlights: ["Moraine Lake's color is genuinely unreal", "Elk grazing on Banff's main street", "Icefields Parkway drive"],
    practicalInfo: "Parks Canada pass required. Moraine Lake and Lake Louise require shuttle reservations May-October.",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 31,
    country: "Canada",
    city: "Canmore",
    region: "Alberta",
    visitedYear: 2025,
    coverImageUrl: "/images/travel-canmore.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Canmore is what Banff would be if you took out the tourists and added more locals who actually hike. It's my kind of mountain town.",
    tags: ["North America", "mountains", "hiking", "outdoors"],
    itinerary: [
      { day: 1, title: "Ha Ling Peak & Town", activities: ["Ha Ling Peak hike (3-4 hrs, moderate-strenuous)", "Policeman's Creek boardwalk", "Canmore Nordic Centre trails", "Brewpub dinner with mountain views"], tips: "Ha Ling Peak rewards with panoramic Three Sisters mountain views." },
    ],
    highlights: ["Ha Ling Peak views", "More affordable base than Banff", "The Three Sisters from every angle"],
    practicalInfo: "20 min drive from Banff — ideal base camp. No national park fees required to stay in Canmore.",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 32,
    country: "Canada",
    city: "Vancouver",
    region: "British Columbia",
    visitedYear: 2023,
    coverImageUrl: "/images/travel-vancouver.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Vancouver is what happens when a world-class city is surrounded by ocean, mountains, and rainforest. It's one of the most naturally beautiful cities anywhere.",
    tags: ["North America", "nature", "mountains", "food", "city"],
    itinerary: [],
    highlights: ["Stanley Park seawall by bike", "Granville Island Public Market", "Grouse Mountain snowshoe in winter"],
    practicalInfo: "No visa required for US passport holders. Transit is excellent — Skytrain covers most of the city. Book Stanley Park bike rentals in advance in summer.",
    createdAt: "2023-01-01T00:00:00Z",
  },
  {
    id: 33,
    country: "Mexico",
    city: "Tulum",
    region: "Quintana Roo",
    visitedYear: 2025,
    coverImageUrl: "/images/travel-tulum.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Tulum is where Mayan ruins meet Caribbean turquoise water. It's more mystical than magical, and the cenotes will genuinely rearrange your sense of wonder.",
    tags: ["Latin America", "beaches", "ruins", "nature", "cenotes"],
    itinerary: [],
    highlights: ["Cenote swimming — completely unlike anything else", "Tulum ruins above the sea", "Sunrise on the beach before anyone else wakes up"],
    practicalInfo: "No visa required for US passport holders. Rent a bike or scooter to get around — it's the best way to explore the jungle roads.",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 34,
    country: "Mexico",
    city: "Cancun",
    region: "Quintana Roo",
    visitedYear: 2024,
    coverImageUrl: "/images/travel-cancun.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Cancun's hotel zone gets all the attention, but the real magic is just outside it — ancient Mayan sites, incredible food, and that Caribbean water that actually looks like a screensaver.",
    tags: ["Latin America", "beaches", "ruins", "food", "nature"],
    itinerary: [],
    highlights: ["Chichén Itzá day trip — one of the true wonders of the world", "Isla Mujeres for the clearest water you've ever seen", "Street tacos in downtown Cancun"],
    practicalInfo: "No visa required for US passport holders. Easy to get around between hotel zone and downtown. Uber works well. Book Chichén Itzá tickets in advance.",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 35,
    country: "United States",
    city: "Chicago",
    region: "Illinois",
    visitedYear: 2019,
    coverImageUrl: "/images/travel-chicago.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Chicago is home base. The city that shaped everything — from how I think about architecture to what deep dish pizza should be (the answer is: exactly this).",
    tags: ["USA", "home", "city", "architecture"],
    itinerary: [],
    highlights: ["The Riverwalk in summer", "Deep dish at Lou Malnati's", "Michigan Ave architecture boat tour"],
    practicalInfo: "Home base — no itinerary needed.",
    createdAt: "2019-01-01T00:00:00Z",
  },
  {
    id: 36,
    country: "United States",
    city: "Durham",
    region: "North Carolina",
    visitedYear: 2021,
    coverImageUrl: "/images/travel-durham.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Durham's research triangle energy is contagious. Great food, growing tech scene, and a warm Southern hospitality that surprised me.",
    tags: ["USA", "tech", "food", "culture"],
    itinerary: [],
    highlights: ["Durham Food Hall", "American Tobacco Campus", "Duke Gardens in bloom"],
    practicalInfo: "Short drive to Raleigh and Chapel Hill.",
    createdAt: "2021-01-01T00:00:00Z",
  },
  {
    id: 37,
    country: "United States",
    city: "Raleigh",
    region: "North Carolina",
    visitedYear: 2021,
    coverImageUrl: "/images/travel-raleigh.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Raleigh is a great American city doing interesting things quietly. Good coffee, good code, good parks.",
    tags: ["USA", "tech", "outdoors"],
    itinerary: [],
    highlights: ["Pullen Park", "Downtown Raleigh food scene", "North Carolina Museum of Natural Sciences"],
    practicalInfo: "Part of the Research Triangle. Easy to explore alongside Durham.",
    createdAt: "2021-01-01T00:00:00Z",
  },
  {
    id: 38,
    country: "United States",
    city: "Denver",
    region: "Colorado",
    visitedYear: 2025,
    coverImageUrl: "/images/travel-denver.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Denver is the gateway to everything good Colorado has — the Rockies are right there and the city itself is surprisingly vibrant.",
    tags: ["USA", "mountains", "outdoors", "food"],
    itinerary: [],
    highlights: ["Red Rocks Amphitheater", "RiNo Art District", "Union Station Farmers Market"],
    practicalInfo: "Mile High City — expect to get winded. Stay hydrated and give yourself a day to adjust before intense hiking.",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 39,
    country: "United States",
    city: "Estes Park",
    region: "Colorado",
    visitedYear: 2025,
    coverImageUrl: "/images/travel-estes-park.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Estes Park is the gateway to Rocky Mountain National Park — moose sightings included.",
    tags: ["USA", "mountains", "hiking", "wildlife"],
    itinerary: [],
    highlights: ["Trail Ridge Road in RMNP", "Moose sightings at Sprague Lake", "Bear Lake hike"],
    practicalInfo: "Rocky Mountain National Park requires a timed entry reservation in peak season (May-Oct).",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 40,
    country: "United States",
    city: "San Diego",
    region: "California",
    visitedYear: 2021,
    coverImageUrl: "/images/travel-san-diego.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "San Diego is where California is at its most comfortable with itself. Beaches, burritos, craft beer, and year-round perfect weather.",
    tags: ["USA", "beaches", "food", "outdoors"],
    itinerary: [],
    highlights: ["La Jolla Cove", "Mission Beach at sunset", "Balboa Park museums"],
    practicalInfo: "The best burritos in America are in San Diego — specifically the California burrito with fries inside.",
    createdAt: "2021-01-01T00:00:00Z",
  },
  {
    id: 41,
    country: "United States",
    city: "Washington D.C.",
    region: "District of Columbia",
    visitedYear: 2026,
    coverImageUrl: "/images/travel-washington-dc.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "The Smithsonian museums are free and infinite. I could live in DC just to visit them repeatedly.",
    tags: ["USA", "history", "museums", "culture"],
    itinerary: [],
    highlights: ["National Museum of African American History", "National Mall cherry blossoms", "Eastern Market on weekends"],
    practicalInfo: "All Smithsonian museums are free. Metro is easy and covers all the major monuments.",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: 42,
    country: "United States",
    city: "Houston",
    region: "Texas",
    visitedYear: 2025,
    coverImageUrl: "/images/travel-houston.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Houston has the most diverse food scene in America, and I will argue this with anyone. NASA is cool too.",
    tags: ["USA", "food", "culture", "space"],
    itinerary: [],
    highlights: ["NASA Space Center", "Houston Museum of Natural Science", "Diverse food scene — Vietnamese, Nigerian, Tex-Mex"],
    practicalInfo: "Houston sprawls — rent a car. Don't miss the Houston Museum District.",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 43,
    country: "United States",
    city: "Dallas",
    region: "Texas",
    visitedYear: 2026,
    coverImageUrl: "/images/travel-dallas.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Dallas is bigger and more interesting than the jokes suggest — great arts district, a history that demands engagement, and incredible tacos.",
    tags: ["USA", "food", "culture", "arts"],
    itinerary: [],
    highlights: ["Sixth Floor Museum", "Deep Ellum arts district", "Dallas Museum of Art"],
    practicalInfo: "Car is essential in Dallas — it's a spread-out city.",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: 44,
    country: "United States",
    city: "Las Vegas",
    region: "Nevada",
    visitedYear: 2023,
    coverImageUrl: "/images/travel-las-vegas.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Las Vegas is a city that should not exist and fully commits to that energy. Shows, buffets, the Strip at 2am — it's overwhelming in the best way.",
    tags: ["USA", "entertainment", "food", "nightlife"],
    itinerary: [],
    highlights: ["The Strip at night", "World-class shows and entertainment", "Food from every corner of the world"],
    practicalInfo: "Everything is more expensive than it looks. Walk the Strip instead of taking cabs between casinos.",
    createdAt: "2023-01-01T00:00:00Z",
  },
  {
    id: 45,
    country: "United States",
    city: "San Francisco",
    region: "California",
    visitedYear: 2022,
    coverImageUrl: "/images/travel-san-francisco.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "SF is complicated — brilliant and broken in the same breath. The food is extraordinary, the hills are brutal, and the views from every corner are cinematic.",
    tags: ["USA", "tech", "food", "city"],
    itinerary: [],
    highlights: ["Golden Gate Bridge at sunrise", "Ferry Building Farmers Market", "Mission District murals"],
    practicalInfo: "Wear layers — SF microclimates are real. Muni and BART cover most of the city.",
    createdAt: "2022-01-01T00:00:00Z",
  },
  {
    id: 46,
    country: "United States",
    city: "Milwaukee",
    region: "Wisconsin",
    visitedYear: 2020,
    coverImageUrl: "/images/travel-milwaukee.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Milwaukee surprised me completely. Lake Michigan, excellent beer scene, one of the best art museums in the Midwest, and genuine Midwestern warmth.",
    tags: ["USA", "Midwest", "art", "outdoors"],
    itinerary: [],
    highlights: ["Milwaukee Art Museum's Burke Brise Soleil", "Lake Michigan lakefront", "Historic Third Ward"],
    practicalInfo: "Easy 90-minute drive from Chicago. Very underrated weekend trip.",
    createdAt: "2020-01-01T00:00:00Z",
  },
  {
    id: 47,
    country: "United States",
    city: "Gatlinburg",
    region: "Tennessee",
    visitedYear: 2022,
    coverImageUrl: "/images/travel-gatlinburg.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Gatlinburg sits at the edge of the Smoky Mountains and leans into it completely — kitschy, cozy, and the perfect launchpad for some of the best hiking on the East Coast.",
    tags: ["USA", "mountains", "hiking", "nature", "outdoors"],
    itinerary: [],
    highlights: ["Alum Cave Trail in the Smokies", "Firefly synchronization season (book early)", "Clingmans Dome above the clouds"],
    practicalInfo: "Great Smoky Mountains National Park is free to enter. Busy on weekends — go mid-week if possible.",
    createdAt: "2022-01-01T00:00:00Z",
  },
  {
    id: 48,
    country: "United States",
    city: "Savannah",
    region: "Georgia",
    visitedYear: 2026,
    coverImageUrl: "/images/travel-savannah.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Savannah is all Spanish moss and cobblestone squares, where time genuinely seems slower and every block has a ghost story worth hearing.",
    tags: ["USA", "history", "architecture", "culture", "South"],
    itinerary: [],
    highlights: ["Forsyth Park under the Spanish moss", "River Street at dusk", "Ghost tours through the historic district"],
    practicalInfo: "Savannah is very walkable in the historic district. Best visited in spring or fall — summers are hot and humid.",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: 49,
    country: "United States",
    city: "Charleston",
    region: "South Carolina",
    visitedYear: 2026,
    coverImageUrl: "/images/travel-charleston.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Charleston is the American South at its most beautiful and most layered. Pastel row houses, incredible food, a harbor full of history, and warmth in every direction.",
    tags: ["USA", "history", "food", "architecture", "South"],
    itinerary: [],
    highlights: ["Rainbow Row at sunrise", "Husk restaurant (worth every reservation attempt)", "Sullivan's Island beach"],
    practicalInfo: "Best explored on foot in the historic district. Book restaurants well in advance — Charleston's food scene is serious.",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: 50,
    country: "United States",
    city: "Outer Banks",
    region: "North Carolina",
    visitedYear: 2024,
    coverImageUrl: "/images/travel-outer-banks.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "The Outer Banks is a hundred miles of barrier islands, wild ponies, lighthouses, and some of the best sunrises on the East Coast. It never feels like it quite belongs to the mainland.",
    tags: ["USA", "beaches", "nature", "outdoors", "NC"],
    itinerary: [],
    highlights: ["Cape Hatteras Lighthouse", "Wild Mustangs of Corolla", "Jockey's Ridge State Park sand dunes"],
    practicalInfo: "No bridge to the northernmost beaches — 4WD required for Corolla wild horse area. Book early for summer; shoulder season is quieter and equally beautiful.",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 51,
    country: "United States",
    city: "Wilmington",
    region: "North Carolina",
    visitedYear: 2024,
    coverImageUrl: "/images/travel-wilmington.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Wilmington has the walkable charm of a coastal city that hasn't been entirely discovered yet — a riverfront, good food, and Wrightsville Beach just minutes away.",
    tags: ["USA", "beaches", "food", "culture", "NC"],
    itinerary: [],
    highlights: ["Wrightsville Beach at sunrise", "Historic downtown Wilmington riverwalk", "Airlie Gardens in bloom"],
    practicalInfo: "Easy drive from Raleigh. Wrightsville Beach has limited parking in summer — arrive early.",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 52,
    country: "United States",
    city: "Asheville",
    region: "North Carolina",
    visitedYear: 2024,
    coverImageUrl: "/images/travel-western-nc.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Asheville, Boone, the Blue Ridge Parkway — western NC is the part of North Carolina that surprises people. Mountains, waterfalls, breweries, and an arts scene with genuine soul.",
    tags: ["USA", "mountains", "hiking", "nature", "arts", "NC"],
    itinerary: [],
    highlights: ["Blue Ridge Parkway at peak foliage", "Asheville River Arts District", "Hiking to Linville Falls and Hanging Rock"],
    practicalInfo: "Asheville is the hub — explore out from there. Fall foliage season (mid-October) is peak, but busy. Boone makes a great base for hiking in the High Country.",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 53,
    country: "United States",
    city: "Myrtle Beach",
    region: "South Carolina",
    visitedYear: 2024,
    coverImageUrl: "/images/travel-myrtle-beach.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Myrtle Beach is unashamedly fun — mini golf, boardwalk, seafood shacks, and 60 miles of sandy Atlantic coast. It knows exactly what it is and owns it completely.",
    tags: ["USA", "beaches", "food", "entertainment", "South"],
    itinerary: [],
    highlights: ["Sunrise on the Grand Strand", "Calabash-style seafood", "Barefoot Landing at sunset"],
    practicalInfo: "Summer is peak season and crowded — May or September are ideal. The stretch from Myrtle Beach to Pawleys Island is 60 miles of beach access.",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 54,
    country: "United States",
    city: "Atlanta",
    region: "Georgia",
    visitedYear: 2023,
    coverImageUrl: "/images/travel-atlanta.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Atlanta moves fast and doesn't apologize for it — a Southern city that became a global one without losing the warmth, the food, or the music.",
    tags: ["USA", "food", "culture", "city", "South"],
    itinerary: [],
    highlights: ["Ponce City Market", "Martin Luther King Jr. National Historic Site", "The BeltLine on a warm evening"],
    practicalInfo: "Hartsfield-Jackson is the world's busiest airport — getting in is easy. Getting around ATL requires a car or Lyft; MARTA covers basics but not everything.",
    createdAt: "2023-01-01T00:00:00Z",
  },
  {
    id: 55,
    country: "United States",
    city: "Philadelphia",
    region: "Pennsylvania",
    visitedYear: 2024,
    coverImageUrl: "/images/travel-philadelphia.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Philadelphia punches above its weight — incredible food, underrated art museums, and a Revolutionary history you can literally walk through.",
    tags: ["USA", "history", "food", "culture", "city"],
    itinerary: [],
    highlights: ["Reading Terminal Market breakfast", "The Barnes Foundation", "Rocky steps at the Philadelphia Museum of Art"],
    practicalInfo: "Amtrak from NYC is 90 minutes. Very walkable historic district. Go to Reading Terminal Market first thing.",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 56,
    country: "United States",
    city: "Phoenix",
    region: "Arizona",
    visitedYear: 2025,
    coverImageUrl: "/images/travel-phoenix.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Phoenix in the desert is an exercise in scale — the sky is enormous, the mountains jut from flat earth, and every sunset looks like it was designed for social media.",
    tags: ["USA", "desert", "outdoors", "nature"],
    itinerary: [],
    highlights: ["Camelback Mountain hike at sunrise", "Desert Botanical Garden", "Scottsdale Old Town at dusk"],
    practicalInfo: "Do not visit in summer — it is genuinely dangerous heat. October through April is ideal. Car is essential.",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 57,
    country: "United States",
    city: "Sedona",
    region: "Arizona",
    visitedYear: 2025,
    coverImageUrl: "/images/travel-sedona.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Sedona is red rock formations that glow at sunset like they're lit from within. Spiritual energy aside — the hiking alone is reason enough to go.",
    tags: ["USA", "desert", "hiking", "nature", "outdoors"],
    itinerary: [],
    highlights: ["Cathedral Rock hike at golden hour", "Devil's Bridge (worth the permit)", "Vortex sites at sunrise before the crowds"],
    practicalInfo: "Book hiking permits in advance for popular trailheads. Sedona is 2 hours from Phoenix — combine them. Cell service is spotty on trails.",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 58,
    country: "United States",
    city: "Miami",
    region: "Florida",
    visitedYear: 2019,
    coverImageUrl: "/images/travel-miami.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Miami is a city that lives outside — on the beach, at the rooftop bar, in the open-air restaurants. It operates on a timezone that's an hour ahead of the rest of Florida.",
    tags: ["USA", "beaches", "food", "nightlife", "culture"],
    itinerary: [],
    highlights: ["South Beach at sunset", "Wynwood Walls murals", "Versailles Cuban restaurant — always"],
    practicalInfo: "Car or Uber essential — Miami sprawls. Book restaurants well in advance on weekends. Art Basel in December makes the city electric.",
    createdAt: "2019-01-01T00:00:00Z",
  },
  {
    id: 59,
    country: "United States",
    city: "Orlando",
    region: "Florida",
    visitedYear: 2020,
    coverImageUrl: "/images/travel-orlando.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Orlando is more than theme parks — though the theme parks are genuinely spectacular. Universal's Wizarding World made me feel like a kid again without apology.",
    tags: ["USA", "entertainment", "food", "outdoors"],
    itinerary: [],
    highlights: ["Harry Potter World at Universal", "Disney Springs evening walk", "Natural Springs of Florida — springs are everywhere and stunning"],
    practicalInfo: "Rent a car — Orlando without a car is difficult. Summer is hot and crowded; fall is the sweet spot for park visits.",
    createdAt: "2020-01-01T00:00:00Z",
  },
  {
    id: 60,
    country: "United States",
    city: "Seattle",
    region: "Washington",
    visitedYear: 2019,
    coverImageUrl: "/images/travel-seattle.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Seattle is a city that earns its moody reputation but surprises you anyway — Pike Place Market, Mount Rainier on clear days, and coffee that takes itself seriously.",
    tags: ["USA", "food", "culture", "outdoors", "city"],
    itinerary: [],
    highlights: ["Pike Place Market fish throw at dawn", "Mount Rainier on a clear day (worth the drive)", "Capitol Hill coffee crawl"],
    practicalInfo: "It really does rain — pack layers. The Space Needle is touristy but the view is genuinely good. Ferry across Puget Sound is free with a car.",
    createdAt: "2019-01-01T00:00:00Z",
  },
  {
    id: 61,
    country: "United States",
    city: "Los Angeles",
    region: "California",
    visitedYear: 2022,
    coverImageUrl: "/images/travel-los-angeles.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "LA is sprawling and chaotic and endlessly surprising — the food scene alone is worth the trip, and the sunsets over the Pacific never get old.",
    tags: ["USA", "food", "culture", "beaches", "city"],
    itinerary: [],
    highlights: ["Sunset from Griffith Observatory", "Tacos from a truck in East LA", "Santa Monica Pier at golden hour"],
    practicalInfo: "You need a car in LA — full stop. Parking can be brutal. The 405 is always terrible.",
    createdAt: "2022-01-01T00:00:00Z",
  },
  {
    id: 62,
    country: "United States",
    city: "Baltimore",
    region: "Maryland",
    visitedYear: 2023,
    coverImageUrl: "/images/travel-baltimore.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Baltimore surprised me every time — the Inner Harbor is beautiful, the crabs are legendary, and the neighborhoods each have their own distinct personality.",
    tags: ["USA", "food", "history", "city", "culture"],
    itinerary: [],
    highlights: ["Maryland blue crabs at a paper-covered table", "Inner Harbor waterfront walk", "Fells Point neighborhood bars and character"],
    practicalInfo: "Baltimore is very drivable from DC — makes for a great day trip or overnight. Fells Point and Canton are the neighborhoods to eat and drink in.",
    createdAt: "2023-01-01T00:00:00Z",
  },
  {
    id: 63,
    country: "United States",
    city: "Shenandoah",
    region: "Virginia",
    visitedYear: 2024,
    coverImageUrl: "/images/travel-shenandoah.jpg",
    secondaryImageUrl: null,
    galleryImages: [],
    summary: "Shenandoah Valley in the fall is one of those quintessential East Coast experiences — Skyline Drive winding through the Blue Ridge Mountains, all color and cool air.",
    tags: ["USA", "outdoors", "hiking", "nature", "road trip"],
    itinerary: [],
    highlights: ["Skyline Drive in peak fall foliage", "Old Rag Mountain hike", "Whiteoak Canyon waterfall trail"],
    practicalInfo: "Shenandoah is a 2-3 hour drive from Raleigh and about 1.5 from DC. Fall is peak season — book accommodations early. The park entrance fee is worth it for the Skyline Drive access.",
    createdAt: "2024-01-01T00:00:00Z",
  },
];
