import { db, workExperienceTable, travelsTable, speakingTable, craftsTable, writingTable } from "@workspace/db";

async function seed() {
  console.log("Seeding portfolio database...");

  await db.delete(writingTable);
  await db.delete(craftsTable);
  await db.delete(speakingTable);
  await db.delete(travelsTable);
  await db.delete(workExperienceTable);

  // ── Work Experience ────────────────────────────────────────────────────────
  await db.insert(workExperienceTable).values([
    {
      company: "CNA Insurance",
      role: "Software Engineer",
      startDate: "2023-04",
      endDate: null,
      current: true,
      description:
        "Designing and deploying cloud-based web applications for underwriters using React, JavaScript, Java, and Spring. Leading production deployments with zero defects and 100% uptime during business hours. Automating internal workflows and leveraging AI agents to eliminate repetitive manual work.",
      highlights: [
        "Designed and deployed ILAP, a cloud-based web application for underwriters using React, JavaScript, Java, and Spring",
        "Built scalable microservices and integrated APIs, improving interoperability and reducing redundancy across platforms",
        "Authored and maintained API documentation using Postman alongside extensive Confluence resources",
        "Integrated SonarQube into CI/CD pipelines, performing penetration testing and maintaining 97%+ JUnit test coverage",
        "Spearheaded production deployments with zero defects and 100% uptime during business hours",
        "Led migration from Concourse to GitHub Actions, reducing deployment cycles by 25% and automating deployment, test, and environment workflows end-to-end",
        "Built AI agent-powered scripts using Claude to automate database change communication to downstream support teams, eliminating manual coordination handoffs",
      ],
      technologies: ["React", "JavaScript", "Java", "Spring Boot", "SonarQube", "GitHub Actions", "Postman", "Claude", "GitHub Copilot", "Adobe Designer", "Echo API"],
      logoUrl: null,
      location: "Chicago, IL",
    },
    {
      company: "CNA Insurance",
      role: "Associate Software Engineer & Intern Manager",
      startDate: "2021-04",
      endDate: "2023-03",
      current: false,
      description:
        "Developed new product segments for an existing web application and led the internship program — designing curriculum, onboarding new hires, and mentoring interns through their first professional engineering experiences.",
      highlights: [
        "Developed a Restaurant segment generating $4M in new premium within months of launch",
        "Improved API integration, increasing digital activity by 300%",
        "Designed and executed an intern curriculum earning a 98% satisfaction rating",
        "Served as key recruiter, mentor, and manager for summer interns — conducting interviews and overseeing professional development",
        "Authored knowledge transfer documentation on Confluence to support team continuity",
      ],
      technologies: ["Java", "Spring Boot", "React", "JavaScript", "Confluence", "SQL"],
      logoUrl: null,
      location: "Chicago, IL",
    },
    {
      company: "CNA Insurance",
      role: "Associate Software Engineer",
      startDate: "2019-06",
      endDate: "2021-03",
      current: false,
      description:
        "Developed and maintained RESTful APIs for commercial insurance exchanges, contributing to $10M in profits. Built automated testing pipelines and shared knowledge through CNA's internal technology newsletter.",
      highlights: [
        "Developed and maintained RESTful APIs using Java, Kotlin, and Spring Boot, contributing $10M in profits",
        "Automated testing pipelines with Concourse, achieving 99% code coverage",
        "Wrote for CNA's technology newsletter, fostering internal knowledge-sharing and collaboration",
      ],
      technologies: ["Java", "Kotlin", "Spring Boot", "Concourse", "SQL"],
      logoUrl: null,
      location: "Chicago, IL",
    },
    {
      company: "CDW Corporation",
      role: "Application Developer Intern",
      startDate: "2017-06",
      endDate: "2017-08",
      current: false,
      description:
        "Improved efficiency of Java applications using Code Analysis Tools (CAST) and refactored legacy code into a modern REST API.",
      highlights: [
        "Improved code quality of Java applications using CAST, increasing quality by multiple letter grades",
        "Refactored legacy Java code into a modern REST API, improving maintainability and usability",
      ],
      technologies: ["Java", "REST APIs", "CAST"],
      logoUrl: null,
      location: "Vernon Hills, IL",
    },
    {
      company: "UIC — Computer Science: Program Design",
      role: "Undergraduate Teaching Assistant",
      startDate: "2017-01",
      endDate: "2019-05",
      current: false,
      description:
        "Led lab sections and held tutoring office hours to help students understand computer science fundamentals. Saw consistent grade improvements among office hour attendees over the course of each semester.",
      highlights: [
        "Led lab sections and tutoring office hours for CS fundamentals coursework",
        "Observed measurable grade improvements among students who attended office hours regularly",
      ],
      technologies: ["C++", "Python", "Computer Science Education"],
      logoUrl: null,
      location: "Chicago, IL",
    },
    {
      company: "Muslim Women in Technology",
      role: "Co-Founder",
      startDate: "2018-06",
      endDate: null,
      current: true,
      description:
        "Co-founded a 501(c)(3) nonprofit supporting underrepresented women in tech. Organized 20+ tech talks featuring leaders from Google, Meta, and startups, and partnered with organizations like Latinas in Tech and General Assembly.",
      highlights: [
        "Founded a 501(c)(3) nonprofit supporting underrepresented women in technology",
        "Organized 20+ tech talks featuring leaders from Google, Meta, and startups",
        "Partnered with Latinas in Tech and General Assembly to expand community reach",
        "Spoke at industry panels and events to advocate for diversity and inclusion",
      ],
      technologies: ["Community Building", "Event Organization", "DEI", "Nonprofit Leadership"],
      logoUrl: null,
      location: "Chicago, IL",
    },
  ]);
  console.log("  ✓ Work experience seeded");

  // ── Travels ────────────────────────────────────────────────────────────────
  await db.insert(travelsTable).values([
    {
      country: "Japan",
      city: "Tokyo",
      region: "Kanto",
      visitedYear: 2025,
      coverImageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
      summary: "Tokyo is sensory overload in the best possible way — neon lights and quiet temple gardens existing in perfect tension.",
      tags: ["Asia", "food", "culture", "city"],
      itinerary: [
        { day: 1, title: "Arrival & Shibuya", activities: ["Arrive at Narita/Haneda", "Check in Shinjuku hotel", "Shibuya crossing at night", "Ramen dinner"], tips: "Get a Suica IC card at the airport — use it for all trains and convenience stores." },
        { day: 2, title: "Asakusa & Akihabara", activities: ["Senso-ji Temple at dawn", "Nakamise shopping street", "Akihabara electronics district", "Tsukiji Outer Market for sushi"], tips: "Asakusa is best at 7am before the crowds arrive." },
        { day: 3, title: "Harajuku & Shibuya Deep Dive", activities: ["Meiji Shrine", "Harajuku Takeshita Street", "Omotesando for shopping", "TeamLab Borderless digital art"], tips: "Book TeamLab weeks in advance." },
      ],
      highlights: ["Shibuya crossing at midnight is surreal", "Tsukiji sushi at 7am", "Vending machines at every corner"],
      practicalInfo: "No visa required for US passport holders (90 days). Carry cash — Japan is still largely cash-based. IC Suica card is essential.",
    },
    {
      country: "Japan",
      city: "Osaka",
      region: "Kansai",
      visitedYear: 2025,
      coverImageUrl: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=800",
      summary: "Osaka's energy is infectious — a city that lives to eat and laughs louder than anyone else in Japan.",
      tags: ["Asia", "food", "nightlife", "culture"],
      itinerary: [
        { day: 1, title: "Dotonbori & Street Food", activities: ["Dotonbori canal walk", "Takoyaki from Kukuru", "Osaka Castle grounds", "Namba nightlife"], tips: "Dotonbori comes alive after 6pm." },
        { day: 2, title: "Shinsekai & Kuromon Market", activities: ["Kuromon Ichiba Market for breakfast", "Shinsekai district", "Sumiyoshi Taisha shrine", "Kushikatsu dinner"], tips: "Never double-dip the kushikatsu — house rules." },
      ],
      highlights: ["Dotonbori at night", "Takoyaki as a food group", "Friendliest city in Japan"],
      practicalInfo: "40-minute shinkansen from Kyoto. Stay in Namba for walking access to everything.",
    },
    {
      country: "Japan",
      city: "Kyoto",
      region: "Kansai",
      visitedYear: 2025,
      coverImageUrl: "/images/travel-kyoto.jpg",
      summary: "Kyoto in autumn is one of those places that makes you quiet. Every temple, every stone path, every torii gate feels deliberate.",
      tags: ["Asia", "temples", "nature", "history"],
      itinerary: [
        { day: 1, title: "Arashiyama", activities: ["Bamboo Grove at sunrise", "Tenryu-ji Temple garden", "Boat ride on Oi River", "Gion district at dusk"], tips: "Bamboo Grove is magical before 7:30am. After 9am it's crowded." },
        { day: 2, title: "Fushimi Inari & Nishiki", activities: ["Fushimi Inari full hike (3 hrs)", "Kinkaku-ji Golden Pavilion", "Nishiki Market food tour", "Tea ceremony experience"], tips: "Book tea ceremony in advance. Fushimi Inari takes 2-3 hours for the full loop." },
      ],
      highlights: ["Fushimi Inari at sunrise", "Autumn leaves at every shrine", "Kaiseki dinner"],
      practicalInfo: "15 min from Osaka by shinkansen. Rent a bicycle to cover the city. Best in March (cherry blossom) or November (koyo).",
    },
    {
      country: "Italy",
      city: "Rome",
      region: "Lazio",
      visitedYear: 2023,
      coverImageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
      summary: "Rome layers thousands of years on top of each other so naturally that you forget you're eating gelato next to ruins that predate Christianity.",
      tags: ["Europe", "history", "food", "art"],
      itinerary: [
        { day: 1, title: "Ancient Rome", activities: ["Colosseum & Roman Forum (book in advance)", "Palatine Hill", "Gelato near the Pantheon", "Trastevere dinner"], tips: "Book Colosseum tickets weeks ahead." },
        { day: 2, title: "Vatican & Piazzas", activities: ["Vatican Museums & Sistine Chapel (early entry)", "St. Peter's Basilica", "Piazza Navona", "Campo de' Fiori market"], tips: "First entry at Vatican opens at 8am — get there early." },
        { day: 3, title: "Hidden Rome", activities: ["Borghese Gallery (reservation required)", "Trastevere neighborhood walk", "Aperitivo hour", "Cacio e pepe dinner"], tips: "Borghese requires timed entry — book well in advance." },
      ],
      highlights: ["The Pantheon at dawn", "Cacio e pepe done right", "Trastevere cobblestone at dusk"],
      practicalInfo: "No visa required for US passport holders in Schengen zone. Book major museums weeks in advance.",
    },
    {
      country: "Italy",
      city: "Florence",
      region: "Tuscany",
      visitedYear: 2023,
      coverImageUrl: "https://images.unsplash.com/photo-1541370976299-4d24be5d2129?w=800",
      summary: "Florence is smaller than you expect and more beautiful than you can prepare for. Every street corner is a painting.",
      tags: ["Europe", "art", "food", "history"],
      itinerary: [
        { day: 1, title: "Uffizi & Duomo", activities: ["Uffizi Gallery (book in advance)", "Brunelleschi's Dome climb", "Mercato Centrale for lunch", "Ponte Vecchio at golden hour"], tips: "Climb the Duomo dome for the best view of Florence." },
        { day: 2, title: "Oltrarno & Tuscany", activities: ["Pitti Palace & Boboli Gardens", "Oltrarno neighborhood craft shops", "Sunset from Piazzale Michelangelo", "Bistecca alla Fiorentina dinner"], tips: "Piazzale Michelangelo at sunset is unmissable." },
      ],
      highlights: ["Boboli Gardens in morning light", "Gelato from Gelateria dei Neri", "The David (worth every queue)"],
      practicalInfo: "90 minutes from Rome by high-speed train. Florence is walkable — no metro needed.",
    },
    {
      country: "Italy",
      city: "Milan",
      region: "Lombardy",
      visitedYear: 2023,
      coverImageUrl: "https://images.unsplash.com/photo-1520175480921-4edfa2983e0f?w=800",
      summary: "Milan surprised me — I expected fashion runways and got centuries of art, the world's best aperitivo scene, and a city that moves fast but lives well.",
      tags: ["Europe", "fashion", "food", "art"],
      itinerary: [
        { day: 1, title: "Duomo & Design Quarter", activities: ["Duomo di Milano rooftop tour", "Galleria Vittorio Emanuele II", "Aperitivo in Brera district", "Risotto alla Milanese dinner"], tips: "Book Duomo rooftop in advance — worth it for the view." },
        { day: 2, title: "The Last Supper", activities: ["Santa Maria delle Grazie (The Last Supper)", "Sforzesco Castle", "Navigli canals evening stroll", "Spritz and cicchetti"], tips: "Last Supper tickets sell out months ahead — book online before your trip." },
      ],
      highlights: ["The Last Supper in person is surreal", "Aperitivo hour with free snacks everywhere", "Rooftop Duomo views"],
      practicalInfo: "Visa-free in Schengen. Book The Last Supper months in advance — no exceptions.",
    },
    {
      country: "Norway",
      city: "Oslo",
      region: "Eastern Norway",
      visitedYear: 2022,
      coverImageUrl: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=800",
      summary: "Oslo is a city that takes the outdoors seriously. Clean, walkable, and surrounded by fjords and forests — it changed the way I think about city planning.",
      tags: ["Europe", "Scandinavia", "nature", "design"],
      itinerary: [
        { day: 1, title: "Museums & Waterfront", activities: ["Vigeland Sculpture Park", "Viking Ship Museum", "Aker Brygge waterfront", "Seafood dinner"], tips: "Oslo Pass covers most museum entries and transit." },
        { day: 2, title: "Fjord Day Trip", activities: ["Ferry to Bygdøy peninsula", "Fram Museum (polar exploration)", "Kayaking on Oslofjord", "Mathallen Food Hall"], tips: "Fjord kayaking tours run May through September." },
      ],
      highlights: ["Vigeland Park is unlike anything anywhere", "The midnight sun in summer", "Oslofjord by ferry"],
      practicalInfo: "No Schengen visa required. Oslo is expensive — budget €30+ for a meal. Oslo Pass is essential.",
    },
    {
      country: "Switzerland",
      city: "Grindelwald",
      region: "Bernese Oberland",
      visitedYear: 2023,
      coverImageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      summary: "Grindelwald sits in a valley with the Eiger looming over it like a painting. I hiked trails I had no business hiking and felt entirely alive.",
      tags: ["Europe", "mountains", "hiking", "nature"],
      itinerary: [
        { day: 1, title: "Arrival & First Hike", activities: ["Arrive by train from Interlaken", "Bachalpsee Lake hike (4 hrs round trip)", "Dinner in village with Eiger views"], tips: "The Bachalpsee hike is one of the most beautiful in Switzerland." },
        { day: 2, title: "Jungfraujoch", activities: ["Cogwheel train to Jungfraujoch (Top of Europe, 3454m)", "Ice Palace inside the glacier", "Views of Aletsch Glacier", "Return via Kleine Scheidegg"], tips: "Check weather before booking — clouds can obscure all views." },
      ],
      highlights: ["Eiger views from the village square", "Bachalpsee at golden hour", "Jungfraujoch glacier ice palace"],
      practicalInfo: "Accessible by train from Interlaken in 45 minutes. Swiss Travel Pass covers most mountain railways.",
    },
    {
      country: "Switzerland",
      city: "Interlaken",
      region: "Bernese Oberland",
      visitedYear: 2023,
      coverImageUrl: "https://images.unsplash.com/photo-1527004013197-933c4bb611b3?w=800",
      summary: "Interlaken is the adventure sports capital of Switzerland — sandwiched between two lakes and a mountain range that dares you to climb it.",
      tags: ["Europe", "adventure", "mountains", "nature"],
      itinerary: [
        { day: 1, title: "Lakes & Town", activities: ["Boat ride on Lake Brienz", "Höhematte park walk", "Paragliding (book in advance)", "Fondue dinner"], tips: "Paragliding from Beatenberg offers stunning views of both lakes." },
      ],
      highlights: ["Paragliding over two lakes simultaneously", "Train rides through mountain tunnels", "Every direction is a postcard"],
      practicalInfo: "Central hub for the Bernese Oberland region. Book adventure activities in advance in peak summer season.",
    },
    {
      country: "Switzerland",
      city: "Lauterbrunnen",
      region: "Bernese Oberland",
      visitedYear: 2023,
      coverImageUrl: "https://images.unsplash.com/photo-1580137189272-c9379f8864fd?w=800",
      summary: "72 waterfalls tumbling down sheer cliff walls into a valley so green it looks fictional. Lauterbrunnen is the Switzerland no one tells you about.",
      tags: ["Europe", "waterfalls", "nature", "hiking"],
      itinerary: [
        { day: 1, title: "Valley of 72 Waterfalls", activities: ["Staubbach Falls walk", "Trümmelbach Falls (inside the mountain)", "Wengen village by train", "Sunset from valley floor"], tips: "Trümmelbach Falls are inside a mountain — completely unexpected and unmissable." },
      ],
      highlights: ["Waterfalls literally falling off cliffs everywhere", "Trümmelbach inside the mountain", "The valley is Lord of the Rings levels of beautiful"],
      practicalInfo: "Cars are not permitted in the valley — park in Lauterbrunnen and take trains. 15 min from Interlaken.",
    },
    {
      country: "Spain",
      city: "Madrid",
      region: "Community of Madrid",
      visitedYear: 2019,
      coverImageUrl: "https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=800",
      summary: "Madrid has the best art museums in Europe and a lunch culture that lasts until 4pm. I leaned into both completely.",
      tags: ["Europe", "art", "food", "nightlife"],
      itinerary: [
        { day: 1, title: "The Golden Triangle of Art", activities: ["Prado Museum (3+ hours)", "Reina Sofia for Guernica", "Thyssen-Bornemisza", "Tapas in La Latina"], tips: "The Prado alone could take a full day — prioritize your favorite periods." },
        { day: 2, title: "Royal Madrid", activities: ["Royal Palace exterior & gardens", "Mercado de San Miguel", "Retiro Park afternoon", "Late dinner (don't arrive before 9pm)"], tips: "Madrileños don't eat dinner until 10pm. Embrace it." },
      ],
      highlights: ["Guernica at Reina Sofia", "Churros con chocolate at San Ginés", "Retiro Park on a Sunday"],
      practicalInfo: "Schengen visa-free. Madrid is very walkable between major museums. Metro is fast and cheap.",
    },
    {
      country: "Spain",
      city: "Granada",
      region: "Andalusia",
      visitedYear: 2019,
      coverImageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
      summary: "Granada carries centuries of Moorish architecture with breathtaking ease. The Alhambra sits above the city like a crown, and the tapas are free with every drink.",
      tags: ["Europe", "history", "Moorish", "architecture"],
      itinerary: [
        { day: 1, title: "The Alhambra", activities: ["Alhambra Palace & Generalife Gardens (morning slot)", "Alcazaba fortress", "El Bañuelo Arab baths", "Free tapas dinner in El Realejo"], tips: "Book Alhambra tickets months in advance — they sell out constantly." },
        { day: 2, title: "Albaicín & Sacromonte", activities: ["Albaicín neighborhood walking tour", "Mirador de San Nicolás (sunset view of Alhambra)", "Flamenco show in Sacromonte cave", "Arabic tea house in the Moorish quarter"], tips: "Mirador de San Nicolás at sunset with the Alhambra lit up is one of the best views in Europe." },
      ],
      highlights: ["Alhambra palace at sunrise light", "Free tapas culture — only in Granada", "Flamenco in a cave"],
      practicalInfo: "3-hour bus from Seville or 1.5 hours from Malaga. Book Alhambra tickets the moment you confirm your travel dates.",
    },
    {
      country: "Spain",
      city: "Seville",
      region: "Andalusia",
      visitedYear: 2019,
      coverImageUrl: "https://images.unsplash.com/photo-1555993539-1732b0258235?w=800",
      summary: "Seville is the most romantic city in Spain — orange trees, flamenco echoing from bars, and the largest Gothic cathedral in the world.",
      tags: ["Europe", "history", "food", "flamenco"],
      itinerary: [
        { day: 1, title: "Cathedral & Alcázar", activities: ["Seville Cathedral & La Giralda tower climb", "Real Alcázar palace", "Barrio Santa Cruz neighborhood", "Tapas bar crawl"], tips: "Climb La Giralda for 360° views over the city." },
        { day: 2, title: "Triana & Flamenco", activities: ["Triana market breakfast", "Guadalquivir river walk", "Flamenco show at El Arenal or Tablao", "Farewell dinner in Alameda de Hércules"], tips: "Book flamenco shows in advance for good seats." },
      ],
      highlights: ["La Giralda tower at sunset", "Authentic flamenco — not the tourist version", "Orange blossom smell everywhere in spring"],
      practicalInfo: "High-speed train from Madrid (2.5 hours). Seville is best explored on foot or by bicycle.",
    },
    {
      country: "Spain",
      city: "Córdoba",
      region: "Andalusia",
      visitedYear: 2019,
      coverImageUrl: "https://images.unsplash.com/photo-1559564485-bc9b6e44bc1b?w=800",
      summary: "Córdoba's Mezquita is one of the most extraordinary buildings I have ever walked into — a mosque built over by a cathedral, coexisting for centuries.",
      tags: ["Europe", "history", "Moorish", "architecture"],
      itinerary: [
        { day: 1, title: "The Mezquita & Old City", activities: ["Mezquita-Catedral (morning entry)", "Alcázar de los Reyes Cristianos", "Jewish Quarter walk", "Salmorejo lunch (Cordoba's version of gazpacho)"], tips: "The Mezquita is best experienced with a guided tour to understand its layered history." },
      ],
      highlights: ["The Mezquita's forest of red-and-white arches", "The flower-filled patios in May", "Salmorejo is superior gazpacho"],
      practicalInfo: "Day trip from Seville (45 min by high-speed train) or Granada (2 hours). Worth a night if possible.",
    },
    {
      country: "Canada",
      city: "Banff",
      region: "Alberta",
      visitedYear: 2025,
      coverImageUrl: "/images/travel-banff.jpg",
      secondaryImageUrl: "/images/travel-banff-2.jpg",
      summary: "Banff looks like it was designed by someone who had never seen nature before and overcorrected wildly. Turquoise lakes, glacier peaks, elk walking downtown.",
      tags: ["North America", "mountains", "hiking", "nature"],
      itinerary: [
        { day: 1, title: "Lake Louise & Moraine Lake", activities: ["Moraine Lake at sunrise (arrive by 6am)", "Lake Louise shoreline walk", "Fairview Lookout hike", "Banff town evening walk"], tips: "Moraine Lake road requires a Parks Canada shuttle reservation — book months ahead." },
        { day: 2, title: "Icefields Parkway", activities: ["Drive the Icefields Parkway (world's most scenic road)", "Athabasca Glacier walk", "Peyto Lake viewpoint", "Jasper town for dinner"], tips: "Stop at every pullout on Icefields Parkway — every single one." },
      ],
      highlights: ["Moraine Lake's color is genuinely unreal", "Elk grazing on Banff's main street", "Icefields Parkway drive"],
      practicalInfo: "Parks Canada pass required. Moraine Lake and Lake Louise require shuttle reservations May-October.",
    },
    {
      country: "Canada",
      city: "Canmore",
      region: "Alberta",
      visitedYear: 2025,
      coverImageUrl: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800",
      summary: "Canmore is what Banff would be if you took out the tourists and added more locals who actually hike. It's my kind of mountain town.",
      tags: ["North America", "mountains", "hiking", "outdoors"],
      itinerary: [
        { day: 1, title: "Ha Ling Peak & Town", activities: ["Ha Ling Peak hike (3-4 hrs, moderate-strenuous)", "Policeman's Creek boardwalk", "Canmore Nordic Centre trails", "Brewpub dinner with mountain views"], tips: "Ha Ling Peak rewards with panoramic Three Sisters mountain views." },
      ],
      highlights: ["Ha Ling Peak views", "More affordable base than Banff", "The Three Sisters from every angle"],
      practicalInfo: "20 min drive from Banff — ideal base camp. No national park fees required to stay in Canmore.",
    },
    {
      country: "Malaysia",
      city: "Kuala Lumpur",
      region: "Wilayah Persekutuan",
      visitedYear: 2025,
      coverImageUrl: "/images/travel-kuala-lumpur.jpg",
      secondaryImageUrl: "/images/travel-kuala-lumpur-2.jpg",
      summary: "KL is impossibly diverse — Malay, Chinese, Indian, and expat cultures colliding in the most delicious, colorful, chaotic way. I could eat my way through it for weeks.",
      tags: ["Asia", "food", "culture", "city"],
      itinerary: [
        { day: 1, title: "Petronas & City Center", activities: ["Petronas Twin Towers (book sky bridge in advance)", "KLCC Park walk", "Bukit Bintang night market", "Hawker stall dinner — char kway teow and roti canai"], tips: "Book Petronas sky bridge tickets online — they sell out." },
        { day: 2, title: "Batu Caves & Little India", activities: ["Batu Caves Hindu temple climb (272 steps)", "Little India in Brickfields", "Central Market for craft shopping", "Rooftop bar with Twin Towers view at dusk"], tips: "Batu Caves dress modestly — temple etiquette applies." },
      ],
      highlights: ["Petronas at night is iconic for a reason", "Batu Caves is an entire vibe", "The food is unmatched, full stop"],
      practicalInfo: "No visa required for US passport holders (90 days). Grab (rideshare) is essential. English is widely spoken.",
    },
    {
      country: "Singapore",
      city: "Singapore",
      region: "Central Region",
      visitedYear: 2025,
      coverImageUrl: "/images/travel-singapore.jpg",
      secondaryImageUrl: "/images/travel-singapore-2.jpg",
      summary: "Singapore is the most efficient city I have ever visited — impeccably clean, impossibly organized, and full of food that quietly rearranges your expectations.",
      tags: ["Asia", "food", "city", "gardens"],
      itinerary: [
        { day: 1, title: "Gardens & Marina Bay", activities: ["Gardens by the Bay (Flower Dome & Cloud Forest)", "Marina Bay Sands SkyPark for city views", "Hawker Centre dinner — chicken rice & laksa", "Light show at Gardens by the Bay (free, 8pm & 9pm)"], tips: "The light show at Supertrees is free — don't miss it." },
        { day: 2, title: "Neighborhoods", activities: ["Chinatown morning (Sri Mariamman Temple)", "Little India's Mustafa Centre", "Kampong Glam & Sultan Mosque", "Clarke Quay riverfront evening"], tips: "Singapore's neighborhoods are each distinct cultural worlds — walk slowly." },
      ],
      highlights: ["Gardens by the Bay is futuristic and beautiful", "Chicken rice from a hawker stall is a revelation", "Changi Airport is its own attraction"],
      practicalInfo: "No visa required for US passport holders. Singapore is expensive — budget accordingly. MRT is fast and extensive.",
    },
    {
      country: "Indonesia",
      city: "Bali",
      region: "Lesser Sunda Islands",
      visitedYear: 2025,
      coverImageUrl: "/images/travel-bali.jpg",
      secondaryImageUrl: "/images/travel-bali-2.jpg",
      summary: "Bali offers something for everyone but takes something specific from you — it asks you to slow down, and you eventually stop resisting.",
      tags: ["Asia", "beaches", "temples", "yoga"],
      itinerary: [
        { day: 1, title: "Ubud & Rice Terraces", activities: ["Tegallalang Rice Terraces (early morning)", "Ubud Monkey Forest", "Ubud Market for crafts", "Traditional Balinese dance performance"], tips: "Visit Tegallalang before 8am to avoid tour groups." },
        { day: 2, title: "Temple Day", activities: ["Tanah Lot sea temple at sunset", "Uluwatu cliff-top temple", "Kecak fire dance at Uluwatu", "Seminyak beach dinner"], tips: "Kecak dance at Uluwatu at sunset is one of Bali's unmissable experiences — book in advance." },
      ],
      highlights: ["Uluwatu at sunset with the Kecak dance", "Tegallalang rice terraces at golden hour", "Ubud's healing energy is real"],
      practicalInfo: "Visa on arrival for US passport holders (30 days, ~$35). Hire a driver for the day (~$40) rather than relying on Grab.",
    },
    {
      country: "South Korea",
      city: "Seoul",
      region: "Seoul Capital Area",
      visitedYear: 2024,
      coverImageUrl: "https://images.unsplash.com/photo-1538485399081-7191377e8241?w=800",
      summary: "Seoul operates on a different frequency — K-beauty, skincare temples, 4am street food, palaces next to glass skyscrapers, and the best fried chicken of my life.",
      tags: ["Asia", "food", "culture", "K-pop", "city"],
      itinerary: [
        { day: 1, title: "Palaces & Hongdae", activities: ["Gyeongbokgung Palace (try on hanbok)", "Bukchon Hanok Village", "Insadong for craft shopping", "Hongdae nightlife and street food"], tips: "Rent a hanbok at Gyeongbokgung — you get free entry wearing one." },
        { day: 2, title: "Myeongdong & N Seoul Tower", activities: ["Myeongdong for K-beauty shopping", "Namdaemun Market", "N Seoul Tower at sunset", "Korean BBQ dinner in Mapo-gu"], tips: "Korean BBQ is best with a group — go with at least 2 people." },
      ],
      highlights: ["Fried chicken + beer (chimaek) is a food religion here", "Gyeongbokgung Palace in hanbok", "Hongdae at midnight — the whole city is awake"],
      practicalInfo: "No visa required for US passport holders (90 days). T-money card for all public transit. English signage on subway.",
    },
    // US destinations
    {
      country: "United States",
      city: "Chicago",
      region: "Illinois",
      visitedYear: 2019,
      coverImageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800",
      summary: "Chicago is home base. The city that shaped everything — from how I think about architecture to what deep dish pizza should be (the answer is: exactly this).",
      tags: ["USA", "home", "city", "architecture"],
      itinerary: [],
      highlights: ["The Riverwalk in summer", "Deep dish at Lou Malnati's", "Michigan Ave architecture boat tour"],
      practicalInfo: "Home base — no itinerary needed.",
    },
    {
      country: "United States",
      city: "Durham",
      region: "North Carolina",
      visitedYear: 2021,
      coverImageUrl: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800",
      summary: "Durham's research triangle energy is contagious. Great food, growing tech scene, and a warm Southern hospitality that surprised me.",
      tags: ["USA", "tech", "food", "culture"],
      itinerary: [],
      highlights: ["Durham Food Hall", "American Tobacco Campus", "Duke Gardens in bloom"],
      practicalInfo: "Short drive to Raleigh and Chapel Hill.",
    },
    {
      country: "United States",
      city: "Raleigh",
      region: "North Carolina",
      visitedYear: 2021,
      coverImageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
      summary: "Raleigh is a great American city doing interesting things quietly. Good coffee, good code, good parks.",
      tags: ["USA", "tech", "outdoors"],
      itinerary: [],
      highlights: ["Pullen Park", "Downtown Raleigh food scene", "North Carolina Museum of Natural Sciences"],
      practicalInfo: "Part of the Research Triangle. Easy to explore alongside Durham.",
    },
    {
      country: "United States",
      city: "Denver",
      region: "Colorado",
      visitedYear: 2025,
      coverImageUrl: "https://images.unsplash.com/photo-1619856699906-09e1f58c98b1?w=800",
      summary: "Denver is the gateway to everything good Colorado has — the Rockies are right there and the city itself is surprisingly vibrant.",
      tags: ["USA", "mountains", "outdoors", "food"],
      itinerary: [],
      highlights: ["Red Rocks Amphitheater", "RiNo Art District", "Union Station Farmers Market"],
      practicalInfo: "Mile High City — expect to get winded. Stay hydrated and give yourself a day to adjust before intense hiking.",
    },
    {
      country: "United States",
      city: "Estes Park",
      region: "Colorado",
      visitedYear: 2025,
      coverImageUrl: "/images/travel-estes-park.jpg",
      summary: "Estes Park is the gateway to Rocky Mountain National Park — moose sightings included.",
      tags: ["USA", "mountains", "hiking", "wildlife"],
      itinerary: [],
      highlights: ["Trail Ridge Road in RMNP", "Moose sightings at Sprague Lake", "Bear Lake hike"],
      practicalInfo: "Rocky Mountain National Park requires a timed entry reservation in peak season (May-Oct).",
    },
    {
      country: "United States",
      city: "San Diego",
      region: "California",
      visitedYear: 2021,
      coverImageUrl: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=800",
      summary: "San Diego is where California is at its most comfortable with itself. Beaches, burritos, craft beer, and year-round perfect weather.",
      tags: ["USA", "beaches", "food", "outdoors"],
      itinerary: [],
      highlights: ["La Jolla Cove", "Mission Beach at sunset", "Balboa Park museums"],
      practicalInfo: "The best burritos in America are in San Diego — specifically the California burrito with fries inside.",
    },
    {
      country: "United States",
      city: "Washington D.C.",
      region: "District of Columbia",
      visitedYear: 2026,
      coverImageUrl: "https://images.unsplash.com/photo-1501466044931-62695aada8e9?w=800",
      summary: "The Smithsonian museums are free and infinite. I could live in DC just to visit them repeatedly.",
      tags: ["USA", "history", "museums", "culture"],
      itinerary: [],
      highlights: ["National Museum of African American History", "National Mall cherry blossoms", "Eastern Market on weekends"],
      practicalInfo: "All Smithsonian museums are free. Metro is easy and covers all the major monuments.",
    },
    {
      country: "United States",
      city: "Houston",
      region: "Texas",
      visitedYear: 2025,
      coverImageUrl: "/images/travel-houston.jpg",
      summary: "Houston has the most diverse food scene in America, and I will argue this with anyone. NASA is cool too.",
      tags: ["USA", "food", "culture", "space"],
      itinerary: [],
      highlights: ["NASA Space Center", "Houston Museum of Natural Science", "Diverse food scene — Vietnamese, Nigerian, Tex-Mex"],
      practicalInfo: "Houston sprawls — rent a car. Don't miss the Houston Museum District.",
    },
    {
      country: "United States",
      city: "Dallas",
      region: "Texas",
      visitedYear: 2026,
      coverImageUrl: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=800",
      summary: "Dallas is bigger and more interesting than the jokes suggest — great arts district, a history that demands engagement, and incredible tacos.",
      tags: ["USA", "food", "culture", "arts"],
      itinerary: [],
      highlights: ["Sixth Floor Museum", "Deep Ellum arts district", "Dallas Museum of Art"],
      practicalInfo: "Car is essential in Dallas — it's a spread-out city.",
    },
    {
      country: "United States",
      city: "Las Vegas",
      region: "Nevada",
      visitedYear: 2023,
      coverImageUrl: "/images/travel-las-vegas.jpg",
      summary: "Las Vegas is a city that should not exist and fully commits to that energy. Shows, buffets, the Strip at 2am — it's overwhelming in the best way.",
      tags: ["USA", "entertainment", "food", "nightlife"],
      itinerary: [],
      highlights: ["The Strip at night", "World-class shows and entertainment", "Food from every corner of the world"],
      practicalInfo: "Everything is more expensive than it looks. Walk the Strip instead of taking cabs between casinos.",
    },
    {
      country: "United States",
      city: "San Francisco",
      region: "California",
      visitedYear: 2022,
      coverImageUrl: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800",
      summary: "SF is complicated — brilliant and broken in the same breath. The food is extraordinary, the hills are brutal, and the views from every corner are cinematic.",
      tags: ["USA", "tech", "food", "city"],
      itinerary: [],
      highlights: ["Golden Gate Bridge at sunrise", "Ferry Building Farmers Market", "Mission District murals"],
      practicalInfo: "Wear layers — SF microclimates are real. Muni and BART cover most of the city.",
    },
    {
      country: "United States",
      city: "Milwaukee",
      region: "Wisconsin",
      visitedYear: 2020,
      coverImageUrl: "https://images.unsplash.com/photo-1580048915913-4f8f5cb481c4?w=800",
      summary: "Milwaukee surprised me completely. Lake Michigan, excellent beer scene, one of the best art museums in the Midwest, and genuine Midwestern warmth.",
      tags: ["USA", "Midwest", "art", "outdoors"],
      itinerary: [],
      highlights: ["Milwaukee Art Museum's Burke Brise Soleil", "Lake Michigan lakefront", "Historic Third Ward"],
      practicalInfo: "Easy 90-minute drive from Chicago. Very underrated weekend trip.",
    },
    {
      country: "France",
      city: "Paris",
      region: "Île-de-France",
      visitedYear: 2023,
      coverImageUrl: "/images/travel-paris.jpg",
      secondaryImageUrl: "/images/travel-paris-2.jpg",
      summary: "Paris is exactly what everyone says it is, and somehow still manages to exceed expectations. Every arrondissement has a different personality and all of them are beautiful.",
      tags: ["Europe", "food", "art", "city", "culture"],
      itinerary: [],
      highlights: ["Musée d'Orsay over the Louvre", "Canal Saint-Martin neighborhood", "Père Lachaise at golden hour", "Marché des Enfants Rouges"],
      practicalInfo: "Paris Métro is efficient and inexpensive. Get a carnet of 10 tickets. Most museums are closed on Mondays.",
    },
    {
      country: "United Kingdom",
      city: "London",
      region: "England",
      visitedYear: 2025,
      coverImageUrl: "/images/travel-london.jpg",
      secondaryImageUrl: "/images/travel-london-2.jpg",
      summary: "London is a city that earns its reputation every single time. History, culture, incredible food from every corner of the world, and a pace that matches yours.",
      tags: ["Europe", "history", "food", "culture", "city"],
      itinerary: [],
      highlights: ["Borough Market for every kind of food imaginable", "The British Museum (and it's free)", "Walking across Tower Bridge at dusk"],
      practicalInfo: "No visa required for US passport holders (6 months). Oyster card or contactless for the Tube. Mind the gap.",
    },
    {
      country: "United States",
      city: "Los Angeles",
      region: "California",
      visitedYear: 2022,
      coverImageUrl: "/images/travel-los-angeles.jpg",
      summary: "LA is sprawling and chaotic and endlessly surprising — the food scene alone is worth the trip, and the sunsets over the Pacific never get old.",
      tags: ["USA", "food", "culture", "beaches", "city"],
      itinerary: [],
      highlights: ["Sunset from Griffith Observatory", "Tacos from a truck in East LA", "Santa Monica Pier at golden hour"],
      practicalInfo: "You need a car in LA — full stop. Parking can be brutal. The 405 is always terrible.",
    },
    {
      country: "Mexico",
      city: "Tulum",
      region: "Quintana Roo",
      visitedYear: 2025,
      coverImageUrl: "/images/travel-tulum.jpg",
      summary: "Tulum is where Mayan ruins meet Caribbean turquoise water. It's more mystical than magical, and the cenotes will genuinely rearrange your sense of wonder.",
      tags: ["Latin America", "beaches", "ruins", "nature", "cenotes"],
      itinerary: [],
      highlights: ["Cenote swimming — completely unlike anything else", "Tulum ruins above the sea", "Sunrise on the beach before anyone else wakes up"],
      practicalInfo: "No visa required for US passport holders. Rent a bike or scooter to get around — it's the best way to explore the jungle roads.",
    },
    {
      country: "United States",
      city: "Gatlinburg",
      region: "Tennessee",
      visitedYear: 2022,
      coverImageUrl: "/images/travel-gatlinburg.jpg",
      summary: "Gatlinburg sits at the edge of the Smoky Mountains and leans into it completely — kitschy, cozy, and the perfect launchpad for some of the best hiking on the East Coast.",
      tags: ["USA", "mountains", "hiking", "nature", "outdoors"],
      itinerary: [],
      highlights: ["Alum Cave Trail in the Smokies", "Firefly synchronization season (book early)", "Clingmans Dome above the clouds"],
      practicalInfo: "Great Smoky Mountains National Park is free to enter. Busy on weekends — go mid-week if possible.",
    },
    {
      country: "United States",
      city: "Savannah",
      region: "Georgia",
      visitedYear: 2026,
      coverImageUrl: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800",
      summary: "Savannah is all Spanish moss and cobblestone squares, where time genuinely seems slower and every block has a ghost story worth hearing.",
      tags: ["USA", "history", "architecture", "culture", "South"],
      itinerary: [],
      highlights: ["Forsyth Park under the Spanish moss", "River Street at dusk", "Ghost tours through the historic district"],
      practicalInfo: "Savannah is very walkable in the historic district. Best visited in spring or fall — summers are hot and humid.",
    },
    {
      country: "United States",
      city: "Charleston",
      region: "South Carolina",
      visitedYear: 2026,
      coverImageUrl: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800",
      summary: "Charleston is the American South at its most beautiful and most layered. Pastel row houses, incredible food, a harbor full of history, and warmth in every direction.",
      tags: ["USA", "history", "food", "architecture", "South"],
      itinerary: [],
      highlights: ["Rainbow Row at sunrise", "Husk restaurant (worth every reservation attempt)", "Sullivan's Island beach"],
      practicalInfo: "Best explored on foot in the historic district. Book restaurants well in advance — Charleston's food scene is serious.",
    },
    {
      country: "United States",
      city: "Outer Banks",
      region: "North Carolina",
      visitedYear: 2024,
      coverImageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
      summary: "The Outer Banks is a hundred miles of barrier islands, wild ponies, lighthouses, and some of the best sunrises on the East Coast. It never feels like it quite belongs to the mainland.",
      tags: ["USA", "beaches", "nature", "outdoors", "NC"],
      itinerary: [],
      highlights: ["Cape Hatteras Lighthouse", "Wild Mustangs of Corolla", "Jockey's Ridge State Park sand dunes"],
      practicalInfo: "No bridge to the northernmost beaches — 4WD required for Corolla wild horse area. Book early for summer; shoulder season is quieter and equally beautiful.",
    },
    {
      country: "United States",
      city: "Wilmington",
      region: "North Carolina",
      visitedYear: 2024,
      coverImageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800",
      summary: "Wilmington has the walkable charm of a coastal city that hasn't been entirely discovered yet — a riverfront, good food, and Wrightsville Beach just minutes away.",
      tags: ["USA", "beaches", "food", "culture", "NC"],
      itinerary: [],
      highlights: ["Wrightsville Beach at sunrise", "Historic downtown Wilmington riverwalk", "Airlie Gardens in bloom"],
      practicalInfo: "Easy drive from Raleigh. Wrightsville Beach has limited parking in summer — arrive early.",
    },
    {
      country: "United States",
      city: "Western NC",
      region: "North Carolina",
      visitedYear: 2024,
      coverImageUrl: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800",
      summary: "Western NC — Asheville, Boone, the Blue Ridge Parkway — is the part of North Carolina that surprises people. Mountains, waterfalls, breweries, and an arts scene with genuine soul.",
      tags: ["USA", "mountains", "hiking", "nature", "arts", "NC"],
      itinerary: [],
      highlights: ["Blue Ridge Parkway at peak foliage", "Asheville River Arts District", "Hiking to Linville Falls and Hanging Rock"],
      practicalInfo: "Asheville is the hub — explore out from there. Fall foliage season (mid-October) is peak, but busy. Boone makes a great base for hiking in the High Country.",
    },
    {
      country: "United States",
      city: "Myrtle Beach",
      region: "South Carolina",
      visitedYear: 2024,
      coverImageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
      summary: "Myrtle Beach is unashamedly fun — mini golf, boardwalk, seafood shacks, and 60 miles of sandy Atlantic coast. It knows exactly what it is and owns it completely.",
      tags: ["USA", "beaches", "food", "entertainment", "South"],
      itinerary: [],
      highlights: ["Sunrise on the Grand Strand", "Calabash-style seafood", "Barefoot Landing at sunset"],
      practicalInfo: "Summer is peak season and crowded — May or September are ideal. The stretch from Myrtle Beach to Pawleys Island is 60 miles of beach access.",
    },
    {
      country: "United States",
      city: "Atlanta",
      region: "Georgia",
      visitedYear: 2023,
      coverImageUrl: "https://images.unsplash.com/photo-1575917649705-5b59aaa12e6b?w=800",
      summary: "Atlanta moves fast and doesn't apologize for it — a Southern city that became a global one without losing the warmth, the food, or the music.",
      tags: ["USA", "food", "culture", "city", "South"],
      itinerary: [],
      highlights: ["Ponce City Market", "Martin Luther King Jr. National Historic Site", "The BeltLine on a warm evening"],
      practicalInfo: "Hartsfield-Jackson is the world's busiest airport — getting in is easy. Getting around ATL requires a car or Lyft; MARTA covers basics but not everything.",
    },
    {
      country: "United States",
      city: "Philadelphia",
      region: "Pennsylvania",
      visitedYear: 2024,
      coverImageUrl: "https://images.unsplash.com/photo-1569761316261-9a8696fa2ca3?w=800",
      summary: "Philadelphia punches above its weight — incredible food, underrated art museums, and a Revolutionary history you can literally walk through.",
      tags: ["USA", "history", "food", "culture", "city"],
      itinerary: [],
      highlights: ["Reading Terminal Market breakfast", "The Barnes Foundation", "Rocky steps at the Philadelphia Museum of Art"],
      practicalInfo: "Amtrak from NYC is 90 minutes. Very walkable historic district. Go to Reading Terminal Market first thing.",
    },
    {
      country: "United States",
      city: "Phoenix",
      region: "Arizona",
      visitedYear: 2025,
      coverImageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
      summary: "Phoenix in the desert is an exercise in scale — the sky is enormous, the mountains jut from flat earth, and every sunset looks like it was designed for social media.",
      tags: ["USA", "desert", "outdoors", "nature"],
      itinerary: [],
      highlights: ["Camelback Mountain hike at sunrise", "Desert Botanical Garden", "Scottsdale Old Town at dusk"],
      practicalInfo: "Do not visit in summer — it is genuinely dangerous heat. October through April is ideal. Car is essential.",
    },
    {
      country: "United States",
      city: "Sedona",
      region: "Arizona",
      visitedYear: 2025,
      coverImageUrl: "/images/travel-sedona.jpg",
      summary: "Sedona is red rock formations that glow at sunset like they're lit from within. Spiritual energy aside — the hiking alone is reason enough to go.",
      tags: ["USA", "desert", "hiking", "nature", "outdoors"],
      itinerary: [],
      highlights: ["Cathedral Rock hike at golden hour", "Devil's Bridge (worth the permit)", "Vortex sites at sunrise before the crowds"],
      practicalInfo: "Book hiking permits in advance for popular trailheads. Sedona is 2 hours from Phoenix — combine them. Cell service is spotty on trails.",
    },
    {
      country: "Pakistan",
      city: "Karachi",
      region: "Sindh",
      visitedYear: 2022,
      coverImageUrl: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800",
      summary: "Karachi is a city of 15 million that runs on chai, biryani, and an unshakeable sense of itself. Loud, layered, and alive in a way few cities match.",
      tags: ["Asia", "Pakistan", "food", "culture", "city"],
      itinerary: [],
      highlights: ["Clifton Beach at sunset", "Burns Road for the best food in the city", "Mohatta Palace Museum"],
      practicalInfo: "Visa required for US passport holders — apply in advance. Summers are hot; winter (November–February) is ideal. Stay in Defence or Clifton area.",
    },
    {
      country: "Pakistan",
      city: "Lahore",
      region: "Punjab",
      visitedYear: 2022,
      coverImageUrl: "https://images.unsplash.com/photo-1548013146-72479768bada?w=800",
      summary: "Lahore is Pakistan's cultural heart — Mughal architecture, incredible street food, and a creative energy that's impossible to ignore once you've felt it.",
      tags: ["Asia", "Pakistan", "history", "food", "culture"],
      itinerary: [],
      highlights: ["Badshahi Mosque at dawn", "Lahore Fort & Sheesh Mahal", "Food Street in the old city"],
      practicalInfo: "An hour's flight from Karachi. The Old City is best explored by foot or rickshaw — motorized traffic makes driving challenging. Don't miss Cooco's Den.",
    },
    {
      country: "United States",
      city: "Miami",
      region: "Florida",
      visitedYear: 2019,
      coverImageUrl: "https://images.unsplash.com/photo-1514214246283-d427a95c5d2f?w=800",
      summary: "Miami is a city that lives outside — on the beach, at the rooftop bar, in the open-air restaurants. It operates on a timezone that's an hour ahead of the rest of Florida.",
      tags: ["USA", "beaches", "food", "nightlife", "culture"],
      itinerary: [],
      highlights: ["South Beach at sunset", "Wynwood Walls murals", "Versailles Cuban restaurant — always"],
      practicalInfo: "Car or Uber essential — Miami sprawls. Book restaurants well in advance on weekends. Art Basel in December makes the city electric.",
    },
    {
      country: "United States",
      city: "Orlando",
      region: "Florida",
      visitedYear: 2020,
      coverImageUrl: "https://images.unsplash.com/photo-1575931953324-f8a97cf4ee1a?w=800",
      summary: "Orlando is more than theme parks — though the theme parks are genuinely spectacular. Universal's Wizarding World made me feel like a kid again without apology.",
      tags: ["USA", "entertainment", "food", "outdoors"],
      itinerary: [],
      highlights: ["Harry Potter World at Universal", "Disney Springs evening walk", "Natural Springs of Florida — springs are everywhere and stunning"],
      practicalInfo: "Rent a car — Orlando without a car is difficult. Summer is hot and crowded; fall is the sweet spot for park visits.",
    },
    {
      country: "Canada",
      city: "Vancouver",
      region: "British Columbia",
      visitedYear: 2023,
      coverImageUrl: "https://images.unsplash.com/photo-1609825488888-3a766db05542?w=800",
      summary: "Vancouver is what happens when a world-class city is surrounded by ocean, mountains, and rainforest. It's one of the most naturally beautiful cities anywhere.",
      tags: ["North America", "nature", "mountains", "food", "city"],
      itinerary: [],
      highlights: ["Stanley Park seawall by bike", "Granville Island Public Market", "Grouse Mountain snowshoe in winter"],
      practicalInfo: "No visa required for US passport holders. Transit is excellent — Skytrain covers most of the city. Book Stanley Park bike rentals in advance in summer.",
    },
    {
      country: "United States",
      city: "Seattle",
      region: "Washington",
      visitedYear: 2019,
      coverImageUrl: "https://images.unsplash.com/photo-1502175353174-a7a70e73b362?w=800",
      summary: "Seattle is a city that earns its moody reputation but surprises you anyway — Pike Place Market, Mount Rainier on clear days, and coffee that takes itself seriously.",
      tags: ["USA", "food", "culture", "outdoors", "city"],
      itinerary: [],
      highlights: ["Pike Place Market fish throw at dawn", "Mount Rainier on a clear day (worth the drive)", "Capitol Hill coffee crawl"],
      practicalInfo: "It really does rain — pack layers. The Space Needle is touristy but the view is genuinely good. Ferry across Puget Sound is free with a car.",
    },
  ]);
  console.log("  ✓ Travels seeded");

  // ── Speaking ───────────────────────────────────────────────────────────────
  await db.insert(speakingTable).values([
    {
      eventName: "WiTech",
      talkTitle: "Navigating Tech as a Muslim Woman in STEM",
      date: "2022-10-01",
      location: "Virtual",
      format: "conference talk",
      audience: "Women in tech, underrepresented minorities in STEM",
      description:
        "Spoke about navigating the tech industry as a Muslim woman, building community through Muslim Women in Technology, and what it takes to show up authentically in spaces not designed for you.",
      slidesUrl: null,
      recordingUrl: "https://www.youtube.com/watch?v=JD13XPwAg74",
      imageUrl: "/images/speaking-panel.jpg",
      upcoming: false,
    },
    {
      eventName: "Techstars Startup Week Chicago",
      talkTitle: "Building in Public: Lessons from a First-Gen Founder",
      date: "2021-09-20",
      location: "Chicago, IL",
      format: "conference talk",
      audience: "Startup founders, entrepreneurs, aspiring builders",
      description:
        "Shared lessons from co-founding Muslim Women in Technology — the realities of building a nonprofit from scratch, community-led growth, and what no one tells you about being a first-generation founder.",
      slidesUrl: null,
      recordingUrl: "https://techstarsstartupweekchicago2021a.sched.com/directory/speakers",
      imageUrl: null,
      upcoming: false,
    },
    {
      eventName: "8th Grade Commencement Ceremony",
      talkTitle: "8th Grade Commencement Address",
      date: "2021-06-01",
      location: "Villa Park, IL",
      format: "keynote",
      audience: "8th grade graduates, families, faculty",
      description:
        "Delivered the commencement address to graduating 8th graders — speaking on identity, resilience, and what it means to carry your community with you as you grow.",
      slidesUrl: null,
      recordingUrl: null,
      imageUrl: null,
      upcoming: false,
    },
    {
      eventName: "South Asian Wedding Events",
      talkTitle: "Wedding & Event Emcee",
      date: "2020-01-01",
      location: "Chicago Metro Area & Beyond",
      format: "emcee",
      audience: "Wedding guests, families, event attendees",
      description:
        "Emceed multiple South Asian wedding events and cultural celebrations — keeping the energy alive, honoring traditions, and making every moment feel personal and memorable for families.",
      slidesUrl: null,
      recordingUrl: null,
      imageUrl: "/images/speaking-stage.jpg",
      upcoming: false,
    },
    {
      eventName: "Coffee, Careers & Connections — Muslim Women's Alliance",
      talkTitle: "Coffee, Careers & Connections",
      date: "2019-10-27",
      location: "Doubletree Hotel, Oak Brook, IL",
      format: "panel",
      audience: "Muslim women professionals, students, career-changers",
      description:
        "Panelist at the Muslim Women's Alliance's Coffee, Careers & Connections event — a professional networking and mentorship afternoon bringing together Muslim women across industries to share career journeys, offer guidance, and build community.",
      slidesUrl: null,
      recordingUrl: null,
      imageUrl: "/images/speaking-mwa-flyer.jpg",
      upcoming: false,
    },
    {
      eventName: "Anita Borg Institute Chicago (ABIdotCHI)",
      talkTitle: "Speaker — Anita Borg Institute Chicago",
      date: "2016-01-01",
      location: "Google Chicago, Chicago, IL",
      format: "conference talk",
      audience: "Tech students, early-career engineers, women in computing",
      description:
        "Speaker at ABIdotCHI — the Chicago chapter of the Anita Borg Institute, an organization dedicated to advancing women in technology. A community event bringing together women and underrepresented technologists to connect, learn, and lift each other up. Hosted at Google Chicago.",
      slidesUrl: null,
      recordingUrl: null,
      imageUrl: null,
      upcoming: false,
    },
  ]);
  console.log("  ✓ Speaking engagements seeded");

  // ── Crafts ─────────────────────────────────────────────────────────────────
  await db.insert(craftsTable).values([
    {
      name: "Custom Chip Bags",
      category: "party favors",
      description:
        "Personalized chip bags designed for parties, baby showers, weddings, graduations, and any celebration worth commemorating. Custom names, dates, photos, and color schemes — every bag is designed from scratch.",
      imageUrl: "/images/craft-chips-bag.jpg",
      tags: ["custom", "party", "personalized", "gift"],
      featured: true,
    },
    {
      name: "Custom Signage & Banners",
      category: "signage",
      description:
        "Hand-designed custom signs and banners for events, home décor, and business use. Welcome signs, seating charts, milestone banners, and one-of-a-kind pieces for any occasion.",
      imageUrl: "/images/craft-signage.jpg",
      tags: ["signage", "custom", "events", "home decor"],
      featured: true,
    },
    {
      name: "Custom Jewelry Boxes",
      category: "custom gifts",
      description:
        "Personalized jewelry boxes and bridesmaid gift sets — monogrammed, hand-lettered, and curated with care. Perfect for weddings, bridal parties, and anyone who deserves something special.",
      imageUrl: "/images/craft-jewelry-box.png",
      tags: ["custom", "gifts", "wedding", "personalized"],
      featured: true,
    },
    {
      name: "Custom Gift Bouquets",
      category: "custom gifts",
      description:
        "Curated gift bundles and custom bouquets designed to feel personal and intentional. From bridal party sets to milestone celebrations, every piece is thoughtfully assembled.",
      imageUrl: "/images/craft-gift-bouquet.jpg",
      tags: ["gifts", "custom", "bouquet", "events"],
      featured: true,
    },
    {
      name: "Event Tablescapes & Signage",
      category: "events",
      description:
        "Full event styling — coordinated tablescapes, custom welcome signs, seating charts, and décor that transforms any venue into something memorable. South Asian weddings and multicultural celebrations a specialty.",
      imageUrl: "/images/craft-tablescape-signage.jpg",
      tags: ["events", "wedding", "tablescape", "signage"],
      featured: true,
    },
    {
      name: "Event Tablescapes",
      category: "events",
      description:
        "Styled tablescapes and centerpiece coordination for intimate dinners, bridal showers, and large-scale events. Elevated, cohesive, and built around your vision.",
      imageUrl: "/images/craft-tablescape-2.jpg",
      tags: ["events", "tablescape", "styling", "wedding"],
      featured: false,
    },
  ]);
  console.log("  ✓ Crafts seeded");

  // ── Writing ────────────────────────────────────────────────────────────────
  await db.insert(writingTable).values([
    {
      title: "What It Actually Takes to Co-Found a Nonprofit While Working Full-Time",
      slug: "co-founding-nonprofit-while-working-full-time",
      excerpt:
        "Muslim Women in Technology didn't start with a grant or a team. It started with a group chat, a gap we couldn't stop noticing, and a stubborn refusal to wait for someone else to fix it.",
      content:
        "Muslim Women in Technology didn't start with a grant or a team. It started with a group chat, a gap we couldn't stop noticing, and a stubborn refusal to wait for someone else to fix it.\n\nI was a few years into my career when it became clear: the support systems I needed didn't exist. The technical mentorship pipelines mostly led elsewhere. The communities for women in tech didn't always feel like they were built with people like me in mind.\n\nSo we built our own.\n\nWhat nobody tells you about starting something from scratch while working full-time:\n\nYou will question the timing constantly. There is never a perfect time. There is just the time you decide to start.\n\nThe people who show up early are everything. Our first ten members set the culture that the next thousand inherited.\n\nSustainability is a practice, not a destination. Burnout isn't noble — it's a sign you haven't built systems yet.\n\nFive years later, MWiT has hosted 20+ tech talks, partnered with organizations we once admired from a distance, and created a community that shows up for each other in ways I didn't think were possible in professional spaces.\n\nBuild the table you wish existed. Someone is waiting for it.",
      publishedAt: "2024-03-15",
      tags: ["nonprofit", "community", "career", "leadership", "Muslim Women in Tech"],
      readingTimeMinutes: 8,
      imageUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800",
      draft: false,
    },
    {
      title: "Solo Travel as a Muslim Woman: What I Research Before Every Trip",
      slug: "solo-travel-muslim-woman-research",
      excerpt:
        "Every trip I take requires a checklist most travel blogs don't mention. Here's what actually goes into preparing to travel solo as a visibly Muslim woman — and why I still go, every time.",
      content:
        "Every trip I take requires a checklist most travel blogs don't mention.\n\nBefore I book a flight, I'm already researching: What are the local attitudes toward Muslim women? Is there a mosque or halal food nearby? What's the political climate? Is solo travel common for women in this country? Will my headscarf make me a target or be completely unremarkable?\n\nMost travel content is written for people who don't have to ask these questions. That's not a complaint — it's just a gap I fill on my own.\n\nHere's what I've learned after visiting 15+ countries solo:\n\nThe fear is often louder than the reality. Japan, Spain, Canada, Switzerland — I found warmth and curiosity almost everywhere I showed up.\n\nCommunity travels with you. I always look for Muslim-owned businesses, local mosques, and fellow travelers who share my background. You find your people everywhere if you know where to look.\n\nThe joy is always bigger than the caution. Every time I almost talked myself out of a trip, I went anyway. Every time, I came back changed.\n\nI travel because the world is larger than the story I was handed — and I want to read every page.",
      publishedAt: "2024-05-20",
      tags: ["travel", "solo travel", "Muslim", "identity", "women"],
      readingTimeMinutes: 10,
      imageUrl: "https://images.unsplash.com/photo-1488085061387-422e29b40080?w=800",
      draft: false,
    },
    {
      title: "On Mentoring Interns: The 98% Satisfaction Rating Was Not an Accident",
      slug: "mentoring-interns-what-actually-works",
      excerpt:
        "The intern program I built at CNA got a 98% satisfaction rating. Here's what went into it — and what most companies get completely wrong about technical mentorship.",
      content:
        "The intern program I designed got a 98% satisfaction rating. That number didn't happen by accident.\n\nMost intern programs make the same mistake: they treat interns as temporary hands and forget they're permanent representatives of your company's culture.\n\nWhat I built instead:\n\nA structured curriculum, not busywork. Every week had a theme — not just 'help with tickets,' but deliberate exposure to different parts of the stack, different teams, different problems.\n\nReal ownership, scoped appropriately. Interns built features that shipped. Not toy features — actual things users saw. That changes how seriously they take the work.\n\nSpaces for honest feedback. Weekly 1:1s weren't status updates. They were 'what's confusing? what's not landing? what do you need that you haven't asked for yet?'\n\nCelebrating the non-technical wins. The day an intern stopped apologizing before every question was the milestone I celebrated most.\n\nA 98% satisfaction rating means something went right. But more than that — it meant people left with something they could actually use. That's the bar.",
      publishedAt: "2024-07-10",
      tags: ["mentorship", "internship", "career", "engineering", "leadership"],
      readingTimeMinutes: 7,
      imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800",
      draft: false,
    },
  ]);
  console.log("  ✓ Writing posts seeded");

  console.log("\nPortfolio database seeded successfully!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
